-- THIS FILE WAS AUTOMATICALLY GENERATED BY TileZed
local overlayMap = {}
overlayMap.VERSION = 1
overlayMap["pert_bar_01_3"] = {{ name = "other", tiles = {"pert_bar_01_92", "pert_bar_01_100"} }}
overlayMap["pert_bar_01_5"] = {{ name = "other", tiles = {"pert_bar_01_93", "pert_bar_01_101"} }}
overlayMap["pert_bar_01_69"] = {{ name = "other", tiles = {"pert_bar_01_95", "pert_bar_01_103"} }}
overlayMap["pert_bar_01_78"] = {{ name = "other", tiles = {"pert_bar_01_94", "pert_bar_01_102"} }}
overlayMap["pert_bar_01_83"] = {{ name = "other", tiles = {"pert_bar_01_92", "pert_bar_01_100"} }}
overlayMap["pert_bar_01_85"] = {{ name = "other", tiles = {"pert_bar_01_93", "pert_bar_01_101"} }}
overlayMap["pert_re-phoenix_4_35"] = {{ name = "other", tiles = {"pert_re-phoenix_4_36", "pert_re-phoenix_4_36"} }}
overlayMap["pert_re-phoenix_4_40"] = {{ name = "other", tiles = {"pert_re-phoenix_4_42", "pert_re-phoenix_4_42"} }}
overlayMap["pert_re-phoenix_4_41"] = {{ name = "other", tiles = {"pert_re-phoenix_4_43", "pert_re-phoenix_4_43"} }}
overlayMap["pert_re-phoenix_4_54"] = {{ name = "other", tiles = {"pert_re-phoenix_4_55", "pert_re-phoenix_4_55"} }}
overlayMap["pert_re-phoenix_4_63"] = {{ name = "other", tiles = {"pert_re-phoenix_4_62", "pert_re-phoenix_4_62"} }}
overlayMap["pert_re-phoenix_5_16"] = {{ name = "other", tiles = {"pert_re-phoenix_5_18", "pert_re-phoenix_5_20"} }}
overlayMap["pert_re-phoenix_5_17"] = {{ name = "other", tiles = {"pert_re-phoenix_5_19", "pert_re-phoenix_5_21"} }}
overlayMap["pert_re-phoenix_5_22"] = {{ name = "other", tiles = {"pert_re-phoenix_5_23", "pert_re-phoenix_5_23"} }}
overlayMap["pert_re-phoenix_5_48"] = {{ name = "other", tiles = {"pert_re-phoenix_5_52", "pert_re-phoenix_5_54"} }}
overlayMap["pert_re-phoenix_5_49"] = {{ name = "other", tiles = {"pert_re-phoenix_5_53", "pert_re-phoenix_5_55"} }}
overlayMap["pert_re-phoenix_5_56"] = {{ name = "other", tiles = {"pert_re-phoenix_5_58", "pert_re-phoenix_5_60"} }}
overlayMap["pert_re-phoenix_5_57"] = {{ name = "other", tiles = {"pert_re-phoenix_5_59", "pert_re-phoenix_5_61"} }}
overlayMap["pert_re-phoenix_5_64"] = {{ name = "other", tiles = {"pert_re-phoenix_5_62", "pert_re-phoenix_5_71"} }}
overlayMap["pert_re-phoenix_5_65"] = {{ name = "other", tiles = {"pert_re-phoenix_5_63", "pert_re-phoenix_5_71"} }}
overlayMap["pert_re-phoenix_5_66"] = {{ name = "other", tiles = {"pert_re-phoenix_5_62", "pert_re-phoenix_5_71"} }}
overlayMap["pert_re-phoenix_5_67"] = {{ name = "other", tiles = {"pert_re-phoenix_5_79", "pert_re-phoenix_5_70"} }}
overlayMap["pert_re-phoenix_5_68"] = {{ name = "other", tiles = {"pert_re-phoenix_5_78", "pert_re-phoenix_5_70"} }}
overlayMap["pert_re-phoenix_5_69"] = {{ name = "other", tiles = {"pert_re-phoenix_5_79", "pert_re-phoenix_5_70"} }}
overlayMap["pert_re-phoenix_5_102"] = {{ name = "other", tiles = {"pert_re-phoenix_5_111", "pert_re-phoenix_5_103"} }}

if not TILEZED then
	getContainerOverlays():addOverlays(overlayMap)
end

return overlayMap
