-- THIS FILE WAS AUTOMATICALLY GENERATED BY TileZed
local overlayMap = {}
overlayMap.VERSION = 1
overlayMap["pert_cyberdrive_systems_1_0"] = {{ name = "other", chance = 2, usage = "", tiles = {"desks_01_2", "desks_01_8", "desks_01_32", "desks_01_29", "desks_01_49", "desks_01_56", "desks_01_88", "desks_01_84", "desks_01_72", "desks_01_35", "desks_01_36", "desks_01_37", "desks_01_38", "desks_01_39", "desks_01_43", "desks_01_44", "desks_01_45", "desks_01_46", "desks_01_47", "desks_01_51", "desks_01_52", "desks_01_53", "desks_01_54", "desks_01_55"} }}
overlayMap["pert_cyberdrive_systems_1_1"] = {{ name = "other", chance = 2, usage = "", tiles = {"desks_01_92", "desks_01_93", "desks_01_94", "desks_01_95"} }}
overlayMap["pert_cyberdrive_systems_1_5"] = {{ name = "other", chance = 3, usage = "", tiles = {"desks_01_9", "desks_01_10", "desks_01_11", "desks_01_12", "desks_01_13", "desks_01_14", "desks_01_15", "desks_01_17", "desks_01_18", "desks_01_19", "desks_01_20", "desks_01_21", "desks_01_22", "desks_01_23"} }}
overlayMap["pert_cyberdrive_systems_1_6"] = {{ name = "other", chance = 3, usage = "", tiles = {"desks_01_24", "desks_01_25", "desks_01_26", "desks_01_27", "desks_01_28", "desks_01_16", "desks_01_30", "desks_01_31", "desks_01_33", "desks_01_34"} }}
overlayMap["pert_cyberdrive_systems_1_8"] = {{ name = "other", chance = 3, usage = "", tiles = {"desks_01_57", "desks_01_58", "desks_01_59", "desks_01_60", "desks_01_61", "desks_01_62", "desks_01_63", "desks_01_65", "desks_01_66", "desks_01_67", "desks_01_68", "desks_01_69", "desks_01_70", "desks_01_71"} }}
overlayMap["pert_cyberdrive_systems_1_10"] = {{ name = "other", chance = 2, usage = "", tiles = {"desks_01_64", "desks_01_73", "desks_01_74", "desks_01_75", "desks_01_76", "desks_01_77", "desks_01_78", "desks_01_79", "desks_01_85", "desks_01_86", "desks_01_87", "desks_01_80", "desks_01_81", "desks_01_82", "desks_01_83", "desks_01_89", "desks_01_90", "desks_01_91"} }}
overlayMap["pert_cyberdrive_systems_1_13"] = {{ name = "other", chance = 3, usage = "", tiles = {"desks_01_3", "desks_01_4", "desks_01_5", "desks_01_6", "desks_01_7", "desks_01_1", "desks_01_0"} }}
overlayMap["pert_cyberdrive_systems_1_14"] = {{ name = "other", chance = 3, usage = "", tiles = {"desks_01_40", "desks_01_41", "desks_01_42", "desks_01_48", "desks_01_50"} }}
overlayMap["pert_grime_01_72"] = {{ name = "other", chance = 2, usage = "", tiles = {"pert_grime_01_73", "pert_grime_01_74", "pert_grime_01_74", "pert_grime_01_75", "pert_grime_01_76", "pert_grime_01_77"} }}
overlayMap["pert_grime_01_80"] = {{ name = "other", chance = 2, usage = "", tiles = {"pert_grime_01_81", "pert_grime_01_82", "pert_grime_01_83", "pert_grime_01_84", "pert_grime_01_85"} }}
overlayMap["pert_grime_01_88"] = {{ name = "other", chance = 1, usage = "", tiles = {"pert_grime_01_89", "pert_grime_01_90", "pert_grime_01_91", "pert_grime_01_92", "pert_grime_01_93"} }}
overlayMap["pert_gross_stuff_01_0"] = {{ name = "other", chance = 2, usage = "", tiles = {"pert_gross_stuff_01_16", "pert_gross_stuff_01_12"} }}
overlayMap["pert_gross_stuff_01_1"] = {{ name = "other", chance = 2, usage = "", tiles = {"pert_gross_stuff_01_13", "pert_gross_stuff_01_17"} }}
overlayMap["pert_gross_stuff_01_2"] = {{ name = "other", chance = 2, usage = "", tiles = {"pert_gross_stuff_01_18", "pert_gross_stuff_01_14"} }}
overlayMap["pert_gross_stuff_01_3"] = {{ name = "other", chance = 2, usage = "", tiles = {"pert_gross_stuff_01_19", "pert_gross_stuff_01_15"} }}
overlayMap["pert_gross_stuff_01_4"] = {{ name = "other", chance = 2, usage = "", tiles = {"pert_gross_stuff_01_16", "pert_gross_stuff_01_12"} }}
overlayMap["pert_gross_stuff_01_5"] = {{ name = "other", chance = 2, usage = "", tiles = {"pert_gross_stuff_01_17", "pert_gross_stuff_01_13"} }}
overlayMap["pert_gross_stuff_01_6"] = {{ name = "other", chance = 2, usage = "", tiles = {"pert_gross_stuff_01_18", "pert_gross_stuff_01_14"} }}
overlayMap["pert_gross_stuff_01_7"] = {{ name = "other", chance = 2, usage = "", tiles = {"pert_gross_stuff_01_19", "pert_gross_stuff_01_15"} }}
overlayMap["pert_gross_stuff_01_8"] = {{ name = "other", chance = 2, usage = "", tiles = {"pert_gross_stuff_01_16", "pert_gross_stuff_01_12"} }}
overlayMap["pert_gross_stuff_01_9"] = {{ name = "other", chance = 2, usage = "", tiles = {"pert_gross_stuff_01_17", "pert_gross_stuff_01_13"} }}
overlayMap["pert_gross_stuff_01_10"] = {{ name = "other", chance = 2, usage = "", tiles = {"pert_gross_stuff_01_18", "pert_gross_stuff_01_14"} }}
overlayMap["pert_gross_stuff_01_11"] = {{ name = "other", chance = 2, usage = "", tiles = {"pert_gross_stuff_01_19", "pert_gross_stuff_01_15"} }}

if not TILEZED then
	getTileOverlays():addOverlays(overlayMap)
end

return overlayMap
