ContainerButtonIcons = ContainerButtonIcons or {}

local t = {}
t.trunk = getTexture("media/textures/Container_B700_trunk.png")
t.trunkS = getTexture("media/textures/Container_B700_trunkS.png")
t.roofrack = getTexture("media/textures/Item_B700_roofr.png")
t.seatBus = getTexture("media/textures/Item_B700_seat.png")
t.trunkSwat = getTexture("media/textures/Container_F700_swat_trunk.png")
t.trunkBank = getTexture("media/textures/Container_F700_bank_trunk.png")
t.trunkBox = getTexture("media/textures/Container_F700_box_trunk.png")
t.trunkBoxS = getTexture("media/textures/Container_F700_box_storage.png")
t.gunrack = getTexture("media/textures/Container_damn_gunrack.png")
t.guncab = getTexture("media/textures/Container_damn_guncab.png")

ContainerButtonIcons.B700Trunk = t.trunk
ContainerButtonIcons.B700TrunkLeft = t.trunkS
ContainerButtonIcons.B700TrunkRight = t.trunkS
ContainerButtonIcons.B700Roofrack = t.roofrack
ContainerButtonIcons.SeatP1 = t.seatBus
ContainerButtonIcons.SeatP2 = t.seatBus
ContainerButtonIcons.SeatP3 = t.seatBus
ContainerButtonIcons.SeatP4 = t.seatBus
ContainerButtonIcons.SeatP5 = t.seatBus
ContainerButtonIcons.SeatP6 = t.seatBus
ContainerButtonIcons.SeatP7 = t.seatBus
ContainerButtonIcons.SeatP8 = t.seatBus
ContainerButtonIcons.SeatP9 = t.seatBus
ContainerButtonIcons.SeatP10 = t.seatBus
ContainerButtonIcons.SeatP11 = t.seatBus
ContainerButtonIcons.SeatP12 = t.seatBus
ContainerButtonIcons.SeatP13 = t.seatBus
ContainerButtonIcons.SeatP14 = t.seatBus
ContainerButtonIcons.F700TrunkSW = t.trunkSwat
ContainerButtonIcons.F700TrunkBN = t.trunkBank
ContainerButtonIcons.F700TrunkBX = t.trunkBox
ContainerButtonIcons.F700TrunkLeftBX = t.trunkBoxS
ContainerButtonIcons.F700TrunkSWGunrack = t.gunrack
ContainerButtonIcons.F700TrunkSWGuncabinet = t.guncab