require 'Items/ProceduralDistributions'

    -- ATA2.ATAProtectionWheelsChain
    table.insert(ProceduralDistributions.list["CrateMechanics"].items, "ATA2.ATAProtectionWheelsChain");
    table.insert(ProceduralDistributions.list["CrateMechanics"].items, 1);
    table.insert(ProceduralDistributions.list["GarageMechanics"].items, "ATA2.ATAProtectionWheelsChain");
    table.insert(ProceduralDistributions.list["GarageMechanics"].items, 1);
    table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "ATA2.ATAProtectionWheelsChain");
    table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 1);
    table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "ATA2.ATAProtectionWheelsChain");
    table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 1);
    table.insert(ProceduralDistributions.list["MechanicShelfTools"].junk.items, "ATA2.ATAProtectionWheelsChain");
    table.insert(ProceduralDistributions.list["MechanicShelfTools"].junk.items, 1);
    table.insert(ProceduralDistributions.list["MechanicShelfWheels"].items, "ATA2.ATAProtectionWheelsChain");
    table.insert(ProceduralDistributions.list["MechanicShelfWheels"].items, 1);
    table.insert(ProceduralDistributions.list["CrateMetalwork"].items, "ATA2.ATAProtectionWheelsChain");
    table.insert(ProceduralDistributions.list["CrateMetalwork"].items, 1);
    table.insert(ProceduralDistributions.list["GarageMetalwork"].items, "ATA2.ATAProtectionWheelsChain");
    table.insert(ProceduralDistributions.list["GarageMetalwork"].items, 1);
    
    -- ATA2.ATARoofLightItem
    table.insert(ProceduralDistributions.list["CrateMechanics"].items, "ATA2.ATARoofLightItem");
    table.insert(ProceduralDistributions.list["CrateMechanics"].items, 1);
    table.insert(ProceduralDistributions.list["GarageMechanics"].items, "ATA2.ATARoofLightItem");
    table.insert(ProceduralDistributions.list["GarageMechanics"].items, 1);
    table.insert(ProceduralDistributions.list["GarageMetalwork"].items, "ATA2.ATARoofLightItem");
    table.insert(ProceduralDistributions.list["GarageMetalwork"].items, 1);
    table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "ATA2.ATARoofLightItem");
    table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 1);
    table.insert(ProceduralDistributions.list["MechanicShelfElectric"].items, "ATA2.ATARoofLightItem");
    table.insert(ProceduralDistributions.list["MechanicShelfElectric"].items, 1);
    table.insert(ProceduralDistributions.list["MechanicShelfElectric"].junk.items, "ATA2.ATARoofLightItem");
    table.insert(ProceduralDistributions.list["MechanicShelfElectric"].junk.items, 1);
