-- Items:
ATAItems = ATAItems or {}
ATAItems.ATA2ItemContainer = ItemType.register("ATA2:ATA2ItemContainer")
ATAItems.ATABullbarPoliceItem1 = ItemType.register("ATA2:ATABullbarPoliceItem1")
ATAItems.ATABullbar1Item = ItemType.register("ATA2:ATABullbar1Item")
ATAItems.ATABullbar2Item = ItemType.register("ATA2:ATABullbar2Item")
ATAItems.ATABullbar3Item = ItemType.register("ATA2:ATABullbar3Item")
ATAItems.ATAFendersWideItem = ItemType.register("ATA2:ATAFendersWideItem")
ATAItems.ATASkirtsSideItem = ItemType.register("ATA2:ATASkirtsSideItem")
ATAItems.ATAFrontRoofLightItem = ItemType.register("ATA2:ATAFrontRoofLightItem")
ATAItems.ATASpoilerFrontItem = ItemType.register("ATA2:ATASpoilerFrontItem")
ATAItems.ATASpoilerRear1Item = ItemType.register("ATA2:ATASpoilerRear1Item")
ATAItems.ATASpoilerRear2Item = ItemType.register("ATA2:ATASpoilerRear2Item")

ATAItems.ATA150Trunk = ItemType.register("ATA2:ATA150Trunk")--Standard Trunk
ATAItems.ATA200Trunk = ItemType.register("ATA2:ATA200Trunk")--Standard Trunk
ATAItems.ATA250Trunk = ItemType.register("ATA2:ATA250Trunk")--Standard Trunk
ATAItems.ATA300Trunk = ItemType.register("ATA2:ATA300Trunk")--Standard Trunk
ATAItems.ATA400Trunk = ItemType.register("ATA2:ATA400Trunk")--Standard Trunk
ATAItems.ATA500Trunk = ItemType.register("ATA2:ATA500Trunk")--Standard Trunk
ATAItems.ATA600Trunk = ItemType.register("ATA2:ATA600Trunk")--Standard Trunk
ATAItems.ATA700Trunk = ItemType.register("ATA2:ATA700Trunk")--Standard Trunk
ATAItems.ATA800Trunk = ItemType.register("ATA2:ATA800Trunk")--Standard Trunk
ATAItems.ATA900Trunk = ItemType.register("ATA2:ATA900Trunk")--Standard Trunk
ATAItems.ATA1000Trunk = ItemType.register("ATA2:ATA1000Trunk")--Standard Trunk
ATAItems.ATA1100Trunk = ItemType.register("ATA2:ATA1100Trunk")--Standard Trunk
ATAItems.ATA1200Trunk = ItemType.register("ATA2:ATA1200Trunk")--Standard Trunk
ATAItems.ATA150Trunk1 = ItemType.register("ATA2:ATA150Trunk1")--Standard Trunk
ATAItems.ATA200Trunk1 = ItemType.register("ATA2:ATA200Trunk1")--Standard Trunk
ATAItems.ATA250Trunk1 = ItemType.register("ATA2:ATA250Trunk1")--Standard Trunk
ATAItems.ATA300Trunk1 = ItemType.register("ATA2:ATA300Trunk1")--Standard Trunk
ATAItems.ATA400Trunk1 = ItemType.register("ATA2:ATA400Trunk1")--Standard Trunk
ATAItems.ATA500Trunk1 = ItemType.register("ATA2:ATA500Trunk1")--Standard Trunk
ATAItems.ATA600Trunk1 = ItemType.register("ATA2:ATA600Trunk1")--Standard Trunk
ATAItems.ATA700Trunk1 = ItemType.register("ATA2:ATA700Trunk1")--Standard Trunk
ATAItems.ATA800Trunk1 = ItemType.register("ATA2:ATA800Trunk1")--Standard Trunk
ATAItems.ATA900Trunk1 = ItemType.register("ATA2:ATA900Trunk1")--Standard Trunk
ATAItems.ATA1000Trunk1 = ItemType.register("ATA2:ATA1000Trunk1")--Standard Trunk
ATAItems.ATA1100Trunk1 = ItemType.register("ATA2:ATA1100Trunk1")--Standard Trunk
ATAItems.ATA1200Trunk1 = ItemType.register("ATA2:ATA1200Trunk1")--Standard Trunk
ATAItems.ATA150Trunk2 = ItemType.register("ATA2:ATA150Trunk2")--Standard Trunk
ATAItems.ATA200Trunk2 = ItemType.register("ATA2:ATA200Trunk2")--Standard Trunk
ATAItems.ATA250Trunk2 = ItemType.register("ATA2:ATA250Trunk2")--Standard Trunk
ATAItems.ATA300Trunk2 = ItemType.register("ATA2:ATA300Trunk2")--Standard Trunk
ATAItems.ATA400Trunk2 = ItemType.register("ATA2:ATA400Trunk2")--Standard Trunk
ATAItems.ATA500Trunk2 = ItemType.register("ATA2:ATA500Trunk2")--Standard Trunk
ATAItems.ATA600Trunk2 = ItemType.register("ATA2:ATA600Trunk2")--Standard Trunk
ATAItems.ATA700Trunk2 = ItemType.register("ATA2:ATA700Trunk2")--Standard Trunk
ATAItems.ATA800Trunk2 = ItemType.register("ATA2:ATA800Trunk2")--Standard Trunk
ATAItems.ATA900Trunk2 = ItemType.register("ATA2:ATA900Trunk2")--Standard Trunk
ATAItems.ATA1000Trunk2 = ItemType.register("ATA2:ATA1000Trunk2")--Standard Trunk
ATAItems.ATA1100Trunk2 = ItemType.register("ATA2:ATA1100Trunk2")--Standard Trunk
ATAItems.ATA1200Trunk2 = ItemType.register("ATA2:ATA1200Trunk2")--Standard Trunk
ATAItems.ATA150Trunk3 = ItemType.register("ATA2:ATA150Trunk3")--Standard Trunk
ATAItems.ATA200Trunk3 = ItemType.register("ATA2:ATA200Trunk3")--Standard Trunk
ATAItems.ATA250Trunk3 = ItemType.register("ATA2:ATA250Trunk3")--Standard Trunk
ATAItems.ATA300Trunk3 = ItemType.register("ATA2:ATA300Trunk3")--Standard Trunk
ATAItems.ATA400Trunk3 = ItemType.register("ATA2:ATA400Trunk3")--Standard Trunk
ATAItems.ATA500Trunk3 = ItemType.register("ATA2:ATA500Trunk3")--Standard Trunk
ATAItems.ATA600Trunk3 = ItemType.register("ATA2:ATA600Trunk3")--Standard Trunk
ATAItems.ATA700Trunk3 = ItemType.register("ATA2:ATA700Trunk3")--Standard Trunk
ATAItems.ATA800Trunk3 = ItemType.register("ATA2:ATA800Trunk3")--Standard Trunk
ATAItems.ATA900Trunk3 = ItemType.register("ATA2:ATA900Trunk3")--Standard Trunk
ATAItems.ATA1000Trunk3 = ItemType.register("ATA2:ATA1000Trunk3")--Standard Trunk
ATAItems.ATA1100Trunk3 = ItemType.register("ATA2:ATA1100Trunk3")--Standard Trunk
ATAItems.ATA1200Trunk3 = ItemType.register("ATA2:ATA1200Trunk3")--Standard Trunk

ATAItems.ATAProtectionWheelsChain = ItemType.register("ATA2:ATAProtectionWheelsChain")--ATAProtectionWheelsItem

--Note Tchernobill: I do not know what is happening with the double definition (ata folder vs tuning2 folder)
ATAItems.ATARoofLightItem = ItemType.register("ATA2:ATARoofLightItem")--ATARoofLightItem
ATAItems.ATASleepingBag = ItemType.register("ATA2:ATASleepingBag")--ATASleepingBag
ATAItems.TransportCounter = ItemType.register("ATA2:TransportCounter")--TransportCounter
ATAItems.TransportCupboard = ItemType.register("ATA2:TransportCupboard")--TransportCupboard
ATAItems.TransportDrawer = ItemType.register("ATA2:TransportDrawer")--TransportDrawer
ATAItems.TransportFreezer = ItemType.register("ATA2:TransportFreezer")--TransportFreezer
ATAItems.TransportFridge = ItemType.register("ATA2:TransportFridge")--TransportFridge
ATAItems.TransportMedicine = ItemType.register("ATA2:TransportMedicine")--TransportMedicine
ATAItems.TransportMicrowave = ItemType.register("ATA2:TransportMicrowave")--TransportMicrowave
ATAItems.TransportOven = ItemType.register("ATA2:TransportOven")--TransportOven
ATAItems.TransportShelve = ItemType.register("ATA2:TransportShelve")--TransportShelve
ATAItems.TransportSeatBoxWooden = ItemType.register("ATA2:TransportSeatBoxWooden")--TransportSeatBoxWooden
ATAItems.ATAFreestorageTrunk = ItemType.register("ATA2:ATAFreestorageTrunk")--Big Trunk

ATAItems.T500Tank1 = ItemType.register("ATA2:500Tank1")--Storage Tank
ATAItems.T500Tank2 = ItemType.register("ATA2:500Tank2")--Storage Tank
ATAItems.T500Tank3 = ItemType.register("ATA2:500Tank3")--Storage Tank
ATAItems.T1000Tank1 = ItemType.register("ATA2:1000Tank1")--Storage Tank
ATAItems.T1000Tank2 = ItemType.register("ATA2:1000Tank2")--Storage Tank
ATAItems.T1000Tank3 = ItemType.register("ATA2:1000Tank3")--Storage Tank
