-- THIS FILE WAS AUTOMATICALLY GENERATED BY TileZed
local overlayMap = {}
overlayMap.VERSION = 1
overlayMap["pineville_containers_8"] = {{ name = "other", tiles = {"pineville_containers_overlays_8", "pineville_containers_overlays_0"} }}
overlayMap["pineville_containers_9"] = {{ name = "other", tiles = {"pineville_containers_overlays_9", "pineville_containers_overlays_1"} }}
overlayMap["pineville_containers_10"] = {{ name = "other", tiles = {"pineville_containers_overlays_10", "pineville_containers_overlays_2"} }}
overlayMap["pineville_containers_11"] = {{ name = "other", tiles = {"pineville_containers_overlays_11", "pineville_containers_overlays_3"} }}
overlayMap["pineville_containers_16"] = {{ name = "other", tiles = {"pineville_containers_overlays_40", "pineville_containers_overlays_26"} }}
overlayMap["pineville_containers_17"] = {{ name = "other", tiles = {"pineville_containers_overlays_41", "pineville_containers_overlays_27"} }}
overlayMap["pineville_containers_18"] = {{ name = "other", tiles = {"pineville_containers_overlays_42"} }}
overlayMap["pineville_containers_19"] = {{ name = "other", tiles = {"pineville_containers_overlays_43"} }}
overlayMap["pineville_containers_20"] = {{ name = "other", tiles = {"pineville_containers_overlays_50", "pineville_containers_overlays_48"} }}
overlayMap["pineville_containers_21"] = {{ name = "other", tiles = {"pineville_containers_overlays_51", "pineville_containers_overlays_49"} }}
overlayMap["pineville_containers_40"] = {{ name = "other", tiles = {"pineville_containers_overlays_56", "pineville_containers_overlays_56"} }}
overlayMap["pineville_containers_41"] = {{ name = "other", tiles = {"pineville_containers_overlays_57", "pineville_containers_overlays_57"} }}
overlayMap["pineville_containers_42"] = {{ name = "other", tiles = {"pineville_containers_overlays_58", "pineville_containers_overlays_58"} }}
overlayMap["pineville_containers_43"] = {{ name = "other", tiles = {"pineville_containers_overlays_59", "pineville_containers_overlays_59"} }}
overlayMap["pineville_tiles_02_32"] = {{ name = "other", tiles = {"pineville_containers_overlays_20", "pineville_containers_overlays_12"} }}
overlayMap["pineville_tiles_02_33"] = {{ name = "other", tiles = {"pineville_containers_overlays_21", "pineville_containers_overlays_13"} }}
overlayMap["pineville_tiles_02_34"] = {{ name = "other", tiles = {"pineville_containers_overlays_22", "pineville_containers_overlays_14"} }}
overlayMap["pineville_tiles_02_35"] = {{ name = "other", tiles = {"pineville_containers_overlays_23", "pineville_containers_overlays_15"} }}
overlayMap["pineville_tiles_02_36"] = {{ name = "other", tiles = {"pineville_containers_overlays_4", "pineville_containers_overlays_6"} }}
overlayMap["pineville_tiles_02_37"] = {{ name = "other", tiles = {"pineville_containers_overlays_5", "pineville_containers_overlays_7"} }}
overlayMap["pineville_tiles_02_44"] = {{ name = "other", tiles = {"pineville_containers_overlays_52", "pineville_containers_overlays_44"} }}
overlayMap["pineville_tiles_02_45"] = {{ name = "other", tiles = {"pineville_containers_overlays_53", "pineville_containers_overlays_45"} }}
overlayMap["pineville_tiles_02_46"] = {{ name = "other", tiles = {"pineville_containers_overlays_54", "pineville_containers_overlays_46"} }}
overlayMap["pineville_tiles_02_47"] = {{ name = "other", tiles = {"pineville_containers_overlays_55", "pineville_containers_overlays_47"} }}
overlayMap["pineville_tiles_02_48"] = {{ name = "other", tiles = {"pineville_containers_overlays_34", "pineville_containers_overlays_32"} }}
overlayMap["pineville_tiles_02_49"] = {{ name = "other", tiles = {"pineville_containers_overlays_35", "pineville_containers_overlays_33"} }}
overlayMap["pineville_tiles_02_50"] = {{ name = "other", tiles = {"pineville_containers_overlays_24", "pineville_containers_overlays_16"} }}
overlayMap["pineville_tiles_02_51"] = {{ name = "other", tiles = {"pineville_containers_overlays_25", "pineville_containers_overlays_16"} }}
overlayMap["pineville_tiles_02_52"] = {{ name = "other", tiles = {"pineville_containers_overlays_28", "pineville_containers_overlays_36"} }}
overlayMap["pineville_tiles_02_53"] = {{ name = "other", tiles = {"pineville_containers_overlays_29", "pineville_containers_overlays_37"} }}
overlayMap["pineville_tiles_02_54"] = {{ name = "other", tiles = {"pineville_containers_overlays_30", "pineville_containers_overlays_38"} }}
overlayMap["pineville_tiles_02_55"] = {{ name = "other", tiles = {"pineville_containers_overlays_31", "pineville_containers_overlays_39"} }}
overlayMap["pineville_tiles_03_48"] = {{ name = "other", tiles = {"pineville_containers_overlays_01_8", "pineville_containers_overlays_01_0"} }}
overlayMap["pineville_tiles_03_49"] = {{ name = "other", tiles = {"pineville_containers_overlays_01_9", "pineville_containers_overlays_01_1"} }}
overlayMap["pineville_tiles_03_50"] = {{ name = "other", tiles = {"pineville_containers_overlays_01_10", "pineville_containers_overlays_01_2"} }}
overlayMap["pineville_tiles_03_51"] = {{ name = "other", tiles = {"pineville_containers_overlays_01_11", "pineville_containers_overlays_01_3"} }}

if not TILEZED then
	getContainerOverlays():addOverlays(overlayMap)
end

return overlayMap
