-- Vehicle spawn registrations removed: modded vehicles are sold in the server store only.
-- Original entries for TrailerKI5 utility/cargo across
-- parkingstall, trailerpark, bad, junkyard, and trafficjams zones were here.