-- THIS FILE WAS AUTOMATICALLY GENERATED BY TileZed
local overlayMap = {}
overlayMap.VERSION = 1
overlayMap["katana_0"] = {{ name = "other", tiles = {"katana_10", "katana_9"} }}
overlayMap["katana_8"] = {{ name = "other", tiles = {"katana_2", "katana_1"} }}

if not TILEZED then
	getContainerOverlays():addOverlays(overlayMap)
end

return overlayMap
