-- Vehicle spawn registrations removed: modded vehicles are sold in the server store only.
-- Original entries for TrailerKI5 utility/cargo/livestock across
-- parkingstall, trailerpark, bad, junkyard, trafficjams, and farm zones were here.