require "Items/ProceduralDistributions"
-- 63beetleTire
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.63beetleTire");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.1);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.63beetleTire");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.08);
-- 63beetleSmallSpoiler0
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.63beetleSmallSpoiler0");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.1);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.63beetleSmallSpoiler0");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.05);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.63beetleSmallSpoiler0");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.04);