local MockingbirddistributionTable = {
	
    MockingbirdZoneRoom = {
		metal_shelves = {
			procedural = true,
			procList = {
				{name="MockingbirdZoneRoom", min=0, max=99, forceForRooms="MockingbirdZoneRoom"},
			}
		},
    },

	DogFoodFactory = {
		isShop = true,
		rolls = 4,
		items = {
			"CatFoodBag", 10,
			"CatToy", 6,
			"CatTreats", 10,
			"DogChew", 6,
			"Dogfood", 20,
			"Dogfood", 10,
			"DogFoodBag", 10,
			"DogTag_Pet", 1,
			"Leash", 4,
			"Rubberducky", 4,
			"TennisBall", 8,
			"WaterDishEmpty", 4,
			"AnimalBone", 20,
			"AnimalBone", 10,
			"SmallAnimalBone", 50,
			"SmallAnimalBone", 20,
			"SharpBoneFragment", 50,
			"DogFoodBag", 50,
			"DogFoodBag", 20,
			"DogFoodBag", 20,
			"DogFoodBag", 10,
			"DogFoodBag", 10,
			"Dogfood", 50,
			"Dogfood", 20,
			"Dogfood", 20,
			"Dogfood", 10,
			"Dogfood", 10,
			"Apron_White", 8,
			"Fleshing_Tool", 10,
			"Glasses_SafetyGoggles", 10,
			"Gloves_Surgical", 10,
			"Hat_DustMask", 10,
		},
		junk = {
			rolls = 1,
			items = {
				
			}
		}
	},

    CrateTVWide = {
        rolls = 1,
        items = {
            "Base.TvPlasmaScreen", 200,
			"Base.TvLCDScreen", 200,
			"Base.TvPlasmaScreen2", 200,
			"Base.TvLCDScreen2", 200,
			"TvWideScreen", 200,
        },
        junk = {
            rolls = 1,
            items = {
                
            }
        }
    },

	CrateMaps = {
		rolls = 4,
		items = {
			"Base.LouisvilleMap1", 2,
			"Base.LouisvilleMap2", 2,
			"Base.LouisvilleMap3", 2,
			"Base.LouisvilleMap4", 2,
			"Base.LouisvilleMap5", 2,
			"Base.LouisvilleMap6", 2,
			"Base.LouisvilleMap7", 2,
			"Base.LouisvilleMap8", 2,
			"Base.LouisvilleMap9", 2,
			"Base.MuldraughMap", 10,
			"Base.WestpointMap", 10,
			"Base.MarchRidgeMap", 10,
			"Base.RosewoodMap", 10,
			"Base.RiversideMap", 10,
			"Base.MockingbirdMap", 10,
		},
		junk = {
			rolls = 1,
			items = {
				
			}
		}
	},

	CrateMechanics = {
		rolls = 4,
		items = {
			"Base.LouisvilleMap1", 0.05,
			"Base.LouisvilleMap2", 0.05,
			"Base.LouisvilleMap3", 0.05,
			"Base.LouisvilleMap4", 0.05,
			"Base.LouisvilleMap5", 0.05,
			"Base.LouisvilleMap6", 0.05,
			"Base.LouisvilleMap7", 0.05,
			"Base.LouisvilleMap8", 0.05,
			"Base.LouisvilleMap9", 0.05,
			"Base.MarchRidgeMap", 0.4,
			"Base.MuldraughMap", 0.4,
			"Base.RiversideMap", 0.4,
			"Base.RosewoodMap", 0.4,
			"Base.WestpointMap", 0.4,
			"Base.MockingbirdMap", 0.4,
			"BlowerFan", 1,
			"BookMechanic1", 2,
			"BookMechanic2", 1,
			"BookMechanic3", 0.5,
			"BookMechanic4", 0.1,
			"BookMechanic5", 0.05,
			"BlowTorch", 4,
			"Calipers", 2,
			"CarBattery1", 1,
			"ElbowPad_Left_Workman", 1,
			"ElectricWire", 10,
			"Epoxy", 4,
			"FiberglassTape", 4,
			"EngineParts", 20,
			"EngineParts", 10,
			"File", 4,
			"Funnel", 10,
			"HandDrill", 4,
			"Hat_BuildersRespirator", 2,
			"Hat_DustMask", 4,
			"Hat_EarMuff_Protectors", 4,
			"HeavyChain", 8,
			"HeavyChain_Hook", 1,
			"IronBar", 4,
			"IronBarHalf", 6,
			"IronPiece", 10,
			"IronBarQuarter", 8,
			"Jack", 2,
			"Kneepad_Left_Workman", 4,
			-- LargeHook boosted for Testing
			"LargeHook", 10,
			"LightBulb", 10,
			"LightBulbBox", 1,
			"LugWrench", 8,
			"Magazine_Car", 10,
			"MechanicMag1", 1,
			"MechanicMag2", 1,
			"MechanicMag3", 1,
			"MetalworkingChisel", 4,
			"MetalworkingPliers", 0.5,
			"MetalworkingPunch", 4,
			"NormalSuspension1", 1,
			"OldBrake1", 6,
			"OldCarMuffler1", 8,
			"PetrolCanEmpty", 10,
			"Pliers", 8,
			"RespiratorFilters", 2,
			"RubberHose", 10,
			"Screwdriver", 10,
			"SheetMetalSnips", 4,
			"SmallFileSet", 4,
			"SmallPunchSet", 4,
			"SmallSaw", 4,
			"SteelBar", 4,
			"SteelBarHalf", 6,
			"SteelPiece", 10,
			"SteelBarQuarter", 8,
			"TireIron", 4,
			"TirePump", 8,
			"ViseGrips", 4,
			"WeldingMask", 1,
			"Wrench", 8,
		},
		junk = {
			rolls = 1,
			items = {
				
			}
		}
	},

	GasStorageMechanics = {
		isShop = true,
		rolls = 4,
		items = {
			"Base.LouisvilleMap1", 0.05,
			"Base.LouisvilleMap2", 0.05,
			"Base.LouisvilleMap3", 0.05,
			"Base.LouisvilleMap4", 0.05,
			"Base.LouisvilleMap5", 0.05,
			"Base.LouisvilleMap6", 0.05,
			"Base.LouisvilleMap7", 0.05,
			"Base.LouisvilleMap8", 0.05,
			"Base.LouisvilleMap9", 0.05,
			"Base.MarchRidgeMap", 0.4,
			"Base.MuldraughMap", 0.4,
			"Base.RiversideMap", 0.4,
			"Base.RosewoodMap", 0.4,
			"Base.WestpointMap", 0.4,
			"Base.MockingbirdMap", 0.4,
			"BookMechanic1", 10,
			"BookMechanic2", 8,
			"Funnel", 10,
			"HeavyChain", 2,
			"LightBulb", 20,
			"LightBulb", 10,
			"LightBulbBox", 0.1,
			"LugWrench", 4,
			"MechanicMag1", 1,
			"MechanicMag2", 1,
			"MechanicMag3", 1,
			"PetrolCanEmpty", 20,
			"PetrolCanEmpty", 10,
			"RubberHose", 10,
			"TireIron", 4,
			"TirePump", 8,
			"Wrench", 8,
		},
		junk = {
			rolls = 1,
			items = {
				
			}
		}
	},

	Hiker = {
		rolls = 4,
		items = {
			"Bag_ALICEpack", 0.5,
			"Bag_BigHikingBag", 2,
			"Bag_FannyPackFront", 2,
			"Bag_HydrationBackpack", 0.5,
			"Bag_LeatherWaterBag", 1,
			"Bag_NormalHikingBag", 4,
			"Base.LouisvilleMap1", 0.5,
			"Base.LouisvilleMap2", 0.5,
			"Base.LouisvilleMap3", 0.5,
			"Base.LouisvilleMap4", 0.5,
			"Base.LouisvilleMap5", 0.5,
			"Base.LouisvilleMap6", 0.5,
			"Base.LouisvilleMap7", 0.5,
			"Base.LouisvilleMap8", 0.5,
			"Base.LouisvilleMap9", 0.5,
			"Base.MarchRidgeMap", 4,
			"Base.MuldraughMap", 4,
			"Base.RiversideMap", 4,
			"Base.RosewoodMap", 4,
			"Base.WestpointMap", 4,
			"Base.MockingbirdMap", 4,
			"BeefJerky", 8,
			"Candle", 10,
			"Canteen", 10,
			"Cooler", 0.1,
			"FlashLight_AngleHead", 1,
			"Flask", 1,
			"Glasses_Aviators", 2,
			"Glasses_Sun", 4,
			"GranolaBar", 10,
			"HandAxe", 2,
			"Handiknife", 1,
			"HandTorch", 8,
			"Hat_Bandana", 10,
			"Hat_BandanaTINT", 10,
			"Hat_Beany", 10,
			"Hat_BonnieHat", 10,
			"Hat_BonnieHat_CamoGreen", 8,
			"Hat_SummerHat", 8,
			"IceAxe", 1,
			"InsectRepellent", 10,
			"KnifeButterfly", 8,
			"KnifePocket", 1,
			"LargeKnife", 4,
			"Magazine_Outdoors", 10,
			"Matches", 10,
			"Multitool", 0.1,
			"Paperback_Nature", 8,
			"Paperback_Travel", 8,
			"PonchoYellowDOWN", 6,
			"Shirt_CamoGreen", 8,
			"Shirt_Lumberjack", 4,
			"Shirt_Lumberjack_TINT", 4,
			"Shoes_HikingBoots", 10,
			"Shoes_Wellies", 2,
			"Shorts_CamoGreenLong", 8,
			"SleepingBag_BluePlaid_Packed", 2,
			"SleepingBag_Camo_Packed", 1,
			"SleepingBag_Cheap_Blue_Packed", 4,
			"SleepingBag_Cheap_Green2_Packed", 4,
			"SleepingBag_Cheap_Green_Packed", 4,
			"SleepingBag_GreenPlaid_Packed", 2,
			"SleepingBag_Green_Packed", 2,
			"SleepingBag_HighQuality_Brown_Packed", 1,
			"SleepingBag_Spiffo_Packed", 0.05,
			"SleepingBag_RedPlaid_Packed", 2,
			"SmallKnife", 8,
			"Spork", 10,
			"TentBlue_Packed", 0.1,
			"TentBrown_Packed", 0.1,
			"TentGreen_Packed", 0.1,
			"TentYellow_Packed", 0.1,
			"Torch", 4,
			"Trousers_CamoDesert", 6,
			"Tshirt_CamoGreen", 10,
			"WaterBottle", 10,
			"WaterPurificationTablets", 10,
			"Whistle", 2,
		},
		junk = {
			rolls = 1,
			items = {

			}
		}
	},

	MagazineRackMaps = {
		rolls = 4,
		items = {
			"Base.LouisvilleMap1", 1,
			"Base.LouisvilleMap2", 1,
			"Base.LouisvilleMap3", 1,
			"Base.LouisvilleMap4", 1,
			"Base.LouisvilleMap5", 1,
			"Base.LouisvilleMap6", 1,
			"Base.LouisvilleMap7", 1,
			"Base.LouisvilleMap8", 1,
			"Base.LouisvilleMap9", 1,
			"Base.MuldraughMap", 8,
			"Base.WestpointMap", 8,
			"Base.MarchRidgeMap", 8,
			"Base.RosewoodMap", 8,
			"Base.RiversideMap", 8,
			"Base.MockingbirdMap", 8,
		},
		junk = {
			rolls = 1,
			items = {

			}
		}
	},

	SafehouseBookShelf = {
		rolls = 4,
		items = {
			-- Skill Books
			"BookAiming1", 1,
			"BookAiming2", 1,
			"BookAiming3", 1,
			"BookAiming4", 1,
			"BookAiming5", 0.5,
			"BookBlacksmith1", 1,
			"BookBlacksmith2", 1,
			"BookBlacksmith3", 1,
			"BookBlacksmith4", 1,
			"BookBlacksmith5", 0.5,
			"BookButchering1", 1,
			"BookButchering2", 1,
			"BookButchering3", 1,
			"BookButchering4", 1,
			"BookButchering5", 0.5,
			"BookCarpentry1", 1,
			"BookCarpentry2", 1,
			"BookCarpentry3", 1,
			"BookCarpentry4", 1,
			"BookCarpentry5", 0.5,
			"BookCarving1", 1,
			"BookCarving2", 1,
			"BookCarving3", 1,
			"BookCarving4", 1,
			"BookCarving5", 0.5,
			"BookCooking1", 1,
			"BookCooking2", 1,
			"BookCooking3", 1,
			"BookCooking4", 1,
			"BookCooking5", 0.5,
			"BookElectrician1", 1,
			"BookElectrician2", 1,
			"BookElectrician3", 1,
			"BookElectrician4", 1,
			"BookElectrician5", 0.5,
			"BookFarming1", 1,
			"BookFarming2", 1,
			"BookFarming3", 1,
			"BookFarming4", 1,
			"BookFarming5", 0.5,
			"BookFirstAid1", 1,
			"BookFirstAid2", 1,
			"BookFirstAid3", 1,
			"BookFirstAid4", 1,
			"BookFirstAid5", 0.5,
			"BookFishing1", 1,
			"BookFishing2", 1,
			"BookFishing3", 1,
			"BookFishing4", 1,
			"BookFishing5", 0.5,
			"BookFlintKnapping1", 1,
			"BookFlintKnapping2", 1,
			"BookFlintKnapping3", 1,
			"BookFlintKnapping4", 1,
			"BookFlintKnapping5", 0.5,
			"BookForaging1", 1,
			"BookForaging2", 1,
			"BookForaging3", 1,
			"BookForaging4", 1,
			"BookForaging5", 0.5,
			"BookGlassmaking1", 1,
			"BookGlassmaking2", 1,
			"BookGlassmaking3", 1,
			"BookGlassmaking4", 1,
			"BookGlassmaking5", 0.5,
			"BookHusbandry1", 1,
			"BookHusbandry2", 1,
			"BookHusbandry3", 1,
			"BookHusbandry4", 1,
			"BookHusbandry5", 0.5,
			"BookLongBlade1", 1,
			"BookLongBlade2", 1,
			"BookLongBlade3", 1,
			"BookLongBlade4", 1,
			"BookLongBlade5", 0.5,
			"BookMaintenance1", 1,
			"BookMaintenance2", 1,
			"BookMaintenance3", 1,
			"BookMaintenance4", 1,
			"BookMaintenance5", 0.5,
			"BookMasonry1", 1,
			"BookMasonry2", 1,
			"BookMasonry3", 1,
			"BookMasonry4", 1,
			"BookMasonry5", 0.5,
			"BookMechanic1", 1,
			"BookMechanic2", 1,
			"BookMechanic3", 1,
			"BookMechanic4", 1,
			"BookMechanic5", 0.5,
			"BookMetalWelding1", 1,
			"BookMetalWelding2", 1,
			"BookMetalWelding3", 1,
			"BookMetalWelding4", 1,
			"BookMetalWelding5", 0.5,
			"BookPottery1", 1,
			"BookPottery2", 1,
			"BookPottery3", 1,
			"BookPottery4", 1,
			"BookPottery5", 0.5,
			"BookReloading1", 1,
			"BookReloading2", 1,
			"BookReloading3", 1,
			"BookReloading4", 1,
			"BookReloading5", 0.5,
			"BookTailoring1", 1,
			"BookTailoring2", 1,
			"BookTailoring3", 1,
			"BookTailoring4", 1,
			"BookTailoring5", 0.5,
			"BookTracking1", 1,
			"BookTracking2", 1,
			"BookTracking3", 1,
			"BookTracking4", 1,
			"BookTracking5", 0.5,
			"BookTrapping4", 1,
			"BookTrapping5", 0.5,
			-- Magazines
			"ArmorMag1", 1,
			"ArmorMag2", 1,
			"ArmorMag3", 1,
			"ArmorMag4", 1,
			"ArmorMag5", 1,
			"ArmorMag6", 1,
			"ArmorMag7", 1,
			"CookingMag1", 1,
			"CookingMag2", 1,
			"CookingMag3", 1,
			"CookingMag4", 1,
			"CookingMag5", 1,
			"CookingMag6", 1,
			"ElectronicsMag1", 1,
			"ElectronicsMag2", 1,
			"ElectronicsMag3", 1,
			"ElectronicsMag4", 1,
			"ElectronicsMag5", 1,
			"EngineerMagazine1", 1,
			"EngineerMagazine2", 1,
			"FarmingMag1", 1,
			"FarmingMag2", 1,
			"FarmingMag3", 1,
			"FarmingMag4", 1,
			"FarmingMag5", 1,
			"FarmingMag6", 1,
			"FarmingMag7", 1,
			"FarmingMag8", 1,
			"FishingMag1", 1,
			"FishingMag2", 1,
			"GlassmakingMag1", 1,
			"GlassmakingMag2", 1,
			"GlassmakingMag3", 1,
			"HempMag1", 1,
			"HerbalistMag", 1,
			"HuntingMag1", 1,
			"HuntingMag2", 1,
			"HuntingMag3", 1,
			"KeyMag1", 1,
			"KnittingMag1", 1,
			"KnittingMag2", 1,
			"MechanicMag1", 1,
			"MechanicMag2", 1,
			"MechanicMag3", 1,
			"MetalworkMag1", 1,
			"MetalworkMag2", 1,
			"MetalworkMag3", 1,
			"MetalworkMag4", 1,
			"PrimitiveToolMag1", 1,
			"PrimitiveToolMag2", 1,
			"PrimitiveToolMag3", 1,
			"RadioMag1", 1,
			"RadioMag2", 1,
			"RadioMag3", 1,
			"SmithingMag1", 1,
			"SmithingMag10", 1,
			"SmithingMag11", 1,
			"SmithingMag2", 1,
			"SmithingMag3", 1,
			"SmithingMag4", 1,
			"SmithingMag5", 1,
			"SmithingMag6", 1,
			"SmithingMag7", 1,
			"SmithingMag8", 1,
			"SmithingMag9", 1,
			"WeaponMag1", 0.5,
			"WeaponMag2", 0.5,
			"WeaponMag3", 0.5,
			"WeaponMag4", 0.5,
			"WeaponMag5", 0.5,
			"WeaponMag6", 0.5,
			"WeaponMag7", 0.5,
			-- Clippings/Recipes
			"ArmorSchematic", 20,
			"BSToolsSchematic", 20,
			"CookwareSchematic", 20,
			"ExplosiveSchematic", 20,
			"MeleeWeaponSchematic", 20,
			"RecipeClipping", 10,
			"SurvivalSchematic", 20,
			-- Maps
			"LouisvilleMap1", 1,
			"LouisvilleMap2", 1,
			"LouisvilleMap3", 1,
			"LouisvilleMap4", 1,
			"LouisvilleMap5", 1,
			"LouisvilleMap6", 1,
			"LouisvilleMap7", 1,
			"LouisvilleMap8", 1,
			"LouisvilleMap9", 1,
			"MarchRidgeMap", 1,
			"MuldraughMap", 1,
			"RiversideMap", 1,
			"RosewoodMap", 1,
			"WestpointMap", 1,
			"MockingbirdMap", 1,
			-- Electronics/Music/VHS
			"CDplayer", 6,
			"Disc_Retail", 10,
			"VHS_Home", 10,
			"VHS_Retail", 50,
			"VHS_Retail", 20,
			"WalkieTalkie2", 2,
			"WalkieTalkie3", 1,
			-- Literature (Generic)
			"Brochure", 10,
			"Catalog", 10,
			"Diary1", 6,
			"Flier", 10,
			"Journal", 10,
			"LetterHandwritten", 20,
			"Magazine", 10,
			"MagazineCrossword", 8,
			"MagazineWordsearch", 8,
			"Notebook", 20,
			"Photo", 50,
			"Photo", 20,
			"Photo_Secret", 4,
			"Photo_VeryOld", 10,
			-- Special
			"HollowBook_Valuables", 0.01,
		},
		junk = {
			rolls = 1,
			items = {
				"Eraser", 6,
				"MagnifyingGlass", 2,
				"MarkerBlack", 6,
				"Pen", 8,
				"Pencil", 10,
				"PencilSpiffo", 0.1,
				"PenFancy", 1,
				"PenMultiColor", 1,
				"PenLight", 4,
				"PenSpiffo", 0.1,
			}
		},
		maxMap = 1,
		stashChance = 10,
	},

	SafehouseFireplace = {
		rolls = 4,
		items = {
			-- Skill Books
			"BookButchering1", 0.5,
			"BookButchering2", 0.1,
			"BookCarpentry1", 0.5,
			"BookCarpentry2", 0.1,
			"BookCarving1", 0.5,
			"BookCarving2", 0.1,
			"BookCooking1", 0.5,
			"BookCooking2", 0.1,
			"BookElectrician1", 0.5,
			"BookElectrician2", 0.1,
			"BookFarming1", 0.5,
			"BookFarming2", 0.1,
			"BookFirstAid1", 0.5,
			"BookFirstAid2", 0.1,
			"BookFishing1", 0.5,
			"BookFishing2", 0.1,
			"BookForaging1", 0.5,
			"BookForaging2", 0.1,
			"BookGlassmaking1", 0.5,
			"BookGlassmaking2", 0.1,
			"BookHusbandry1", 0.5,
			"BookHusbandry2", 0.1,
			"BookMaintenance1", 0.5,
			"BookMaintenance2", 0.1,
			"BookMasonry1", 0.5,
			"BookMasonry2", 0.1,
			"BookMechanic1", 0.5,
			"BookMechanic2", 0.1,
			"BookMetalWelding1", 0.5,
			"BookMetalWelding2", 0.1,
			"BookPottery1", 0.5,
			"BookPottery2", 0.1,
			"BookTailoring1", 0.5,
			"BookTailoring2", 0.1,
			"BookTracking1", 0.5,
			"BookTracking2", 0.1,
			"BookTrapping1", 0.5,
			"BookTrapping2", 0.1,
			-- Magazines
			"ArmorMag1", 0.05,
			"CookingMag1", 0.1,
			"CookingMag2", 0.1,
			"CookingMag3", 0.1,
			"CookingMag4", 0.1,
			"CookingMag5", 0.1,
			"CookingMag6", 0.1,
			"ElectronicsMag1", 0.1,
			"ElectronicsMag2", 0.1,
			"ElectronicsMag3", 0.1,
			"ElectronicsMag4", 0.1,
			"ElectronicsMag5", 0.1,
			"EngineerMagazine1", 0.1,
			"EngineerMagazine2", 0.1,
			"FarmingMag1", 0.1,
			"FarmingMag2", 0.1,
			"FarmingMag3", 0.1,
			"FarmingMag4", 0.1,
			"FarmingMag5", 0.1,
			"FarmingMag6", 0.1,
			"FarmingMag7", 0.1,
			"FarmingMag8", 0.1,
			"FishingMag1", 0.1,
			"FishingMag2", 0.1,
			"HempMag1", 0.05,
			"HerbalistMag", 0.1,
			"HuntingMag1", 0.1,
			"HuntingMag2", 0.1,
			"HuntingMag3", 0.1,
			"KnittingMag1", 0.1,
			"KnittingMag2", 0.1,
			"MechanicMag1", 0.1,
			"MechanicMag2", 0.1,
			"MechanicMag3", 0.1,
			"MetalworkMag1", 0.1,
			"MetalworkMag2", 0.1,
			"MetalworkMag3", 0.1,
			"MetalworkMag4", 0.1,
			"WeaponMag1", 0.01,
			"WeaponMag2", 0.01,
			"WeaponMag3", 0.01,
			"WeaponMag4", 0.01,
			"WeaponMag5", 0.01,
			"WeaponMag7", 0.01,
			-- Maps
			"LouisvilleMap1", 0.05,
			"LouisvilleMap2", 0.05,
			"LouisvilleMap3", 0.05,
			"LouisvilleMap4", 0.05,
			"LouisvilleMap5", 0.05,
			"LouisvilleMap6", 0.05,
			"LouisvilleMap7", 0.05,
			"LouisvilleMap8", 0.05,
			"LouisvilleMap9", 0.05,
			"MarchRidgeMap", 0.5,
			"MuldraughMap", 0.5,
			"RiversideMap", 0.5,
			"RosewoodMap", 0.5,
			"WestpointMap", 0.5,
			"MockingbirdMap", 0.5,
			-- Literature (Generic)
			"Brochure", 50,
			"Brochure", 20,
			"Catalog", 20,
			"ComicBook_Retail", 8,
			"Flier", 50,
			"Flier", 20,
			"GenericMail", 50,
			"GenericMail", 20,
			"HottieZ", 4,
			"LetterHandwritten", 8,
			"Magazine", 20,
			"Magazine", 10,
			"MagazineCrossword", 8,
			"MagazineWordsearch", 8,
			"Newspaper", 20,
			"Newspaper", 10,
			"Paperwork", 20,
			"Paperwork", 10,
			"Phonebook", 20,
			"RecipeClipping", 8,
			-- Fuel/Flammables
			"BandageDirty", 8,
			"Firewood", 10,
			"Money", 50,
			"Money", 20,
			"Money", 20,
			"Money", 10,
			"MoneyBundle", 4,
			"RippedSheetsDirty", 8,
			"Twigs", 8,
		},
		junk = {
			rolls = 1,
			items = {
				"FireplacePoker", 4,
			}
		},
		maxMap = 1, -- yes, even in the fireplace
		stashChance = 10,
	},

	SafehouseFireplace_Late = {
		rolls = 4,
		items = {
			-- Skill Books
			"BookButchering1", 0.5,
			"BookButchering2", 0.1,
			"BookCarpentry1", 0.5,
			"BookCarpentry2", 0.1,
			"BookCarving1", 0.5,
			"BookCarving2", 0.1,
			"BookCooking1", 0.5,
			"BookCooking2", 0.1,
			"BookElectrician1", 0.5,
			"BookElectrician2", 0.1,
			"BookFarming1", 0.5,
			"BookFarming2", 0.1,
			"BookFirstAid1", 0.5,
			"BookFirstAid2", 0.1,
			"BookFishing1", 0.5,
			"BookFishing2", 0.1,
			"BookForaging1", 0.5,
			"BookForaging2", 0.1,
			"BookGlassmaking1", 0.5,
			"BookGlassmaking2", 0.1,
			"BookHusbandry1", 0.5,
			"BookHusbandry2", 0.1,
			"BookMaintenance1", 0.5,
			"BookMaintenance2", 0.1,
			"BookMasonry1", 0.5,
			"BookMasonry2", 0.1,
			"BookMechanic1", 0.5,
			"BookMechanic2", 0.1,
			"BookMetalWelding1", 0.5,
			"BookMetalWelding2", 0.1,
			"BookPottery1", 0.5,
			"BookPottery2", 0.1,
			"BookTailoring1", 0.5,
			"BookTailoring2", 0.1,
			"BookTracking1", 0.5,
			"BookTracking2", 0.1,
			"BookTrapping1", 0.5,
			"BookTrapping2", 0.1,
			-- Magazines
			"ArmorMag1", 0.05,
			"CookingMag1", 0.1,
			"CookingMag2", 0.1,
			"CookingMag3", 0.1,
			"CookingMag4", 0.1,
			"CookingMag5", 0.1,
			"CookingMag6", 0.1,
			"ElectronicsMag1", 0.1,
			"ElectronicsMag2", 0.1,
			"ElectronicsMag3", 0.1,
			"ElectronicsMag4", 0.1,
			"ElectronicsMag5", 0.1,
			"EngineerMagazine1", 0.1,
			"EngineerMagazine2", 0.1,
			"FarmingMag1", 0.1,
			"FarmingMag2", 0.1,
			"FarmingMag3", 0.1,
			"FarmingMag4", 0.1,
			"FarmingMag5", 0.1,
			"FarmingMag6", 0.1,
			"FarmingMag7", 0.1,
			"FarmingMag8", 0.1,
			"FishingMag1", 0.1,
			"FishingMag2", 0.1,
			"HempMag1", 0.05,
			"HerbalistMag", 0.1,
			"HuntingMag1", 0.1,
			"HuntingMag2", 0.1,
			"HuntingMag3", 0.1,
			"KnittingMag1", 0.1,
			"KnittingMag2", 0.1,
			"MechanicMag1", 0.1,
			"MechanicMag2", 0.1,
			"MechanicMag3", 0.1,
			"MetalworkMag1", 0.1,
			"MetalworkMag2", 0.1,
			"MetalworkMag3", 0.1,
			"MetalworkMag4", 0.1,
			"WeaponMag1", 0.01,
			"WeaponMag2", 0.01,
			"WeaponMag3", 0.01,
			"WeaponMag4", 0.01,
			"WeaponMag5", 0.01,
			"WeaponMag7", 0.01,
			-- Maps
			"LouisvilleMap1", 0.05,
			"LouisvilleMap2", 0.05,
			"LouisvilleMap3", 0.05,
			"LouisvilleMap4", 0.05,
			"LouisvilleMap5", 0.05,
			"LouisvilleMap6", 0.05,
			"LouisvilleMap7", 0.05,
			"LouisvilleMap8", 0.05,
			"LouisvilleMap9", 0.05,
			"MarchRidgeMap", 0.5,
			"MuldraughMap", 0.5,
			"RiversideMap", 0.5,
			"RosewoodMap", 0.5,
			"WestpointMap", 0.5,
			"MockingbirdMap", 0.5,
			-- Literature (Generic)
			"Brochure", 50,
			"Brochure", 20,
			"Catalog", 20,
			"ComicBook_Retail", 8,
			"Flier", 50,
			"Flier", 20,
			"GenericMail", 50,
			"GenericMail", 20,
			"HottieZ", 4,
			"LetterHandwritten", 8,
			"Magazine", 20,
			"Magazine", 10,
			"MagazineCrossword", 8,
			"MagazineWordsearch", 8,
			"Newspaper", 20,
			"Newspaper", 10,
			"Paperwork", 20,
			"Paperwork", 10,
			"Phonebook", 20,
			"RecipeClipping", 8,
			-- Fuel/Flammables
			"BandageDirty", 8,
			"Firewood", 1,
			"Money", 50,
			"Money", 20,
			"Money", 20,
			"Money", 10,
			"MoneyBundle", 4,
			"RippedSheetsDirty", 8,
			"Twigs", 8,
			-- Misc.
			"AnimalBone", 4,
			"JawboneBovide", 2,
			"SharpBoneFragment", 8,
			"SharpBone_Long", 4,
			"SmallAnimalBone", 10,
		},
		junk = {
			rolls = 1,
			items = {
				"FireplacePoker", 4,
			}
		},
		maxMap = 1, -- yes, even in the fireplace
		stashChance = 10,
	},

	StoreShelfMechanics = {
		isShop = true,
		rolls = 4,
		items = {
			"Base.LouisvilleMap1", 0.05,
			"Base.LouisvilleMap2", 0.05,
			"Base.LouisvilleMap3", 0.05,
			"Base.LouisvilleMap4", 0.05,
			"Base.LouisvilleMap5", 0.05,
			"Base.LouisvilleMap6", 0.05,
			"Base.LouisvilleMap7", 0.05,
			"Base.LouisvilleMap8", 0.05,
			"Base.LouisvilleMap9", 0.05,
			"Base.MarchRidgeMap", 0.4,
			"Base.MuldraughMap", 0.4,
			"Base.RiversideMap", 0.4,
			"Base.RosewoodMap", 0.4,
			"Base.WestpointMap", 0.4,
			"Base.MockingbirdMap", 0.4,
			"BookMechanic1", 10,
			"BookMechanic2", 8,
			"Epoxy", 1,
			"FiberglassTape", 1,
			"Funnel", 10,
			"Glasses_Aviators", 2,
			"Glasses_Sun", 10,
			"Gloves_FingerlessLeatherGloves", 2,
			"Gloves_LeatherGloves", 1,
			"Gloves_LeatherGlovesBlack", 1,
			"HeavyChain", 1,
			"LightBulb", 4,
			"LightBulb", 4,
			"LugWrench", 2,
			"Magazine_Car_New", 10,
			"MechanicMag1", 1,
			"MechanicMag2", 1,
			"MechanicMag3", 1,
			"PetrolCanEmpty", 20,
			"PetrolCanEmpty", 10,
			"Ratchet", 10,
			"RubberHose", 10,
			"Screwdriver", 4,
			"TireIron", 2,
			"TirePump", 8,
			"Wrench", 8,
		},
		junk = {
			rolls = 1,
			items = {

			}
		}
	},

}

table.insert(Distributions, 2, MockingbirddistributionTable);