-- Vehicle spawn registrations removed: modded vehicles are sold in the server store only.
-- Original entries for 92amgeneralM998, 92amgeneralM998Burnt, TrailerM101A3cargo across
-- parkingstall, trailerpark, bad, junkyard, ranger, trafficjams, and military zones were here.