objects = {
  { name = "", type = "SpawnPoint", x = 3280, y = 7092, z = 0, width = 1, height = 1, properties = { Professions = "unemployed" } },
  { name = "medium", type = "ParkingStall", x = 3285, y = 7123, z = 0, width = 4, height = 3 },
  { name = "bad", type = "ParkingStall", x = 3105, y = 7189, z = 0, width = 4, height = 3, properties = { Direction = "E" } },
  { name = "medium", type = "ParkingStall", x = 3285, y = 7118, z = 0, width = 4, height = 3 },
  { name = "medium", type = "ParkingStall", x = 3274, y = 6970, z = 0, width = 3, height = 4, properties = { Direction = "N" } },
  { name = "medium", type = "ParkingStall", x = 3285, y = 7086, z = 0, width = 4, height = 3 },
  { name = "medium", type = "ParkingStall", x = 3125, y = 7078, z = 0, width = 3, height = 4, properties = { Direction = "S" } },
  { name = "medium", type = "ParkingStall", x = 3121, y = 7078, z = 0, width = 3, height = 4 },
  { name = "medium", type = "ParkingStall", x = 3285, y = 7091, z = 0, width = 4, height = 3 },
  { name = "parkingstall", type = "ParkingStall", x = 3290, y = 7118, z = 0, width = 4, height = 3 },
  { name = "parkingstall", type = "ParkingStall", x = 3290, y = 7091, z = 0, width = 4, height = 3 },
  { name = "ranger", type = "ParkingStall", x = 3258, y = 6977, z = 0, width = 4, height = 3 },
  { name = "medium", type = "ParkingStall", x = 3291, y = 7143, z = 0, width = 3, height = 4, properties = { Direction = "S" } },
  { name = "parkingstall", type = "ParkingStall", x = 3209, y = 7167, z = 0, width = 3, height = 4, properties = { Direction = "S" } },
  { name = "parkingstall", type = "ParkingStall", x = 3225, y = 7142, z = 0, width = 4, height = 21, properties = { Direction = "E" } },
  { name = "parkingstall", type = "ParkingStall", x = 3176, y = 7142, z = 0, width = 45, height = 4, properties = { Direction = "N" } },
  { name = "", type = "SpawnPoint", x = 3125, y = 7183, z = 0, width = 1, height = 1, properties = { Professions = "farmer,unemployed" } },
  { name = "ranger", type = "ParkingStall", x = 3156, y = 7166, z = 0, width = 4, height = 3, properties = { Direction = "E" } },
  { name = "parkingstall", type = "ParkingStall", x = 3133, y = 7126, z = 0, width = 4, height = 3, properties = { Direction = "W" } },
  { name = "", type = "SpawnPoint", x = 3120, y = 7126, z = 1, width = 1, height = 1, properties = { Professions = "farmer,unemployed" } },
  { name = "", type = "SpawnPoint", x = 3113, y = 7066, z = 0, width = 1, height = 1, properties = { Professions = "unemployed" } },
  { name = "parkingstall", type = "ParkingStall", x = 3270, y = 6974, z = 0, width = 3, height = 4, properties = { Direction = "N" } },
  { name = "parkingstall", type = "ParkingStall", x = 3269, y = 6982, z = 0, width = 4, height = 6, properties = { Direction = "W" } },
  { name = "Wedding", type = "ZombiesType", x = 3080, y = 6966, z = 0, width = 67, height = 59 },
  { name = "Athletic", type = "ZombiesType", x = 3220, y = 7036, z = 0, width = 33, height = 105 },
  { name = "Football", type = "ZombiesType", x = 3192, y = 7036, z = 0, width = 28, height = 106 },
  { name = "Athletic", type = "ZombiesType", x = 3168, y = 7036, z = 0, width = 24, height = 106 },
  { name = "good", type = "ParkingStall", x = 3118, y = 6999, z = 0, width = 4, height = 6, properties = { Direction = "W" } },
  { name = "medium", type = "ParkingStall", x = 3131, y = 6995, z = 0, width = 4, height = 16, properties = { Direction = "E" } },
  { name = "medium", type = "ParkingStall", x = 3206, y = 6974, z = 0, width = 8, height = 3, properties = { Direction = "E" } },
  { name = "medium", type = "ParkingStall", x = 3263, y = 7158, z = 0, width = 6, height = 4, properties = { Direction = "N" } },
  { name = "medium", type = "ParkingStall", x = 3277, y = 7171, z = 0, width = 6, height = 4, properties = { Direction = "S" } },
  { name = "parkingstall", type = "ParkingStall", x = 3262, y = 7169, z = 0, width = 4, height = 6, properties = { Direction = "W" } },
  { name = "", type = "SpawnPoint", x = 3256, y = 7163, z = 0, width = 1, height = 1, properties = { Professions = "farmer" } },
  { name = "", type = "SpawnPoint", x = 3281, y = 7118, z = 0, width = 1, height = 1, properties = { Professions = "unemployed" } },
  { name = "", type = "SpawnPoint", x = 3213, y = 6962, z = 1, width = 1, height = 1, properties = { Professions = "unemployed" } },
  { name = "", type = "SpawnPoint", x = 3238, y = 7086, z = 1, width = 1, height = 1, properties = { Professions = "janitor" } },
  { name = "", type = "SpawnPoint", x = 3238, y = 7091, z = 0, width = 1, height = 1, properties = { Professions = "unemployed" } },
  { name = "", type = "SpawnPoint", x = 3201, y = 7174, z = 1, width = 1, height = 1, properties = { Professions = "unemployed" } },
  { name = "", type = "SpawnPoint", x = 3223, y = 7169, z = 1, width = 1, height = 1, properties = { Professions = "unemployed" } },
  { name = "bad", type = "ParkingStall", x = 3059, y = 6921, z = 0, width = 4, height = 3, properties = { Direction = "E" } },
  { name = "ambulance", type = "ParkingStall", x = 3190, y = 7160, z = 0, width = 8, height = 3, properties = { Direction = "W" } },
  { name = "trafficjamn", type = "ParkingStall", x = 3145, y = 7101, z = 0, width = 3, height = 8, properties = { Direction = "N" } },
  { name = "trafficjams", type = "ParkingStall", x = 3144, y = 7095, z = 0, width = 3, height = 6, properties = { Direction = "S" } },
  { name = "chicken", type = "Ranch", x = 3251, y = 6992, z = 0, width = 12, height = 13 },
  { name = "chicken", type = "Ranch", x = 3151, y = 6958, z = 0, width = 12, height = 11 },
  { name = "Add basement", type = "", x = 3205, y = 6957, z = 0, width = 13, height = 15 },
  { name = "", type = "SpawnPoint", x = 3432, y = 7167, z = 0, width = 1, height = 1, properties = { Professions = "shopclerk" } },
  { name = "", type = "SpawnPoint", x = 3428, y = 7168, z = 0, width = 1, height = 1, properties = { Professions = "securityguard" } },
  { name = "", type = "SpawnPoint", x = 3428, y = 7158, z = 0, width = 1, height = 1, properties = { Professions = "janitor" } },
  { name = "", type = "SpawnPoint", x = 3433, y = 7137, z = 0, width = 1, height = 1, properties = { Professions = "fastfoodcook" } },
  { name = "", type = "SpawnPoint", x = 3427, y = 7137, z = 0, width = 1, height = 1, properties = { Professions = "fastfoodcook" } },
  { name = "", type = "SpawnPoint", x = 3417, y = 7160, z = 0, width = 1, height = 1, properties = { Professions = "salesperson" } },
  { name = "", type = "SpawnPoint", x = 3399, y = 7141, z = 0, width = 1, height = 1, properties = { Professions = "customerservice,shopclerk" } },
  { name = "", type = "SpawnPoint", x = 3399, y = 7137, z = 0, width = 1, height = 1, properties = { Professions = "customerservice" } },
  { name = "", type = "SpawnPoint", x = 3398, y = 7166, z = 0, width = 1, height = 1, properties = { Professions = "salesperson" } },
  { name = "", type = "SpawnPoint", x = 3397, y = 7182, z = 0, width = 1, height = 1, properties = { Professions = "shopclerk" } },
  { name = "", type = "SpawnPoint", x = 3397, y = 7185, z = 0, width = 1, height = 1, properties = { Professions = "constructionworker" } },
  { name = "", type = "SpawnPoint", x = 3433, y = 7187, z = 0, width = 1, height = 1, properties = { Professions = "cashier" } },
  { name = "", type = "SpawnPoint", x = 3416, y = 7177, z = 0, width = 1, height = 1, properties = { Professions = "cashier" } },
  { name = "", type = "SpawnPoint", x = 3423, y = 7177, z = 0, width = 1, height = 1, properties = { Professions = "chef,cook" } },
  { name = "", type = "SpawnPoint", x = 3427, y = 7179, z = 0, width = 1, height = 1, properties = { Professions = "waiter" } },
  { name = "", type = "SpawnPoint", x = 3418, y = 7168, z = 1, width = 1, height = 1, properties = { Professions = "itworker" } },
  { name = "", type = "SpawnPoint", x = 3423, y = 7181, z = 1, width = 1, height = 1, properties = { Professions = "burglar" } },
  { name = "", type = "SpawnPoint", x = 3411, y = 7159, z = 1, width = 1, height = 1, properties = { Professions = "officeworker" } },
  { name = "", type = "SpawnPoint", x = 3411, y = 7168, z = 1, width = 1, height = 1, properties = { Professions = "secretary" } },
  { name = "", type = "SpawnPoint", x = 3422, y = 7165, z = 0, width = 1, height = 1, properties = { Professions = "policeofficer" } },
  { name = "", type = "SpawnPoint", x = 3422, y = 7142, z = 0, width = 1, height = 1, properties = { Professions = "drugdealer" } },
  { name = "", type = "SpawnPoint", x = 3422, y = 7139, z = 0, width = 1, height = 1, properties = { Professions = "unemployed" } },
  { name = "", type = "SpawnPoint", x = 3433, y = 7134, z = 0, width = 1, height = 1, properties = { Professions = "chef" } },
  { name = "", type = "SpawnPoint", x = 3395, y = 7176, z = 0, width = 1, height = 1, properties = { Professions = "burglar,shopclerk" } },
  { name = "", type = "SpawnPoint", x = 3423, y = 7176, z = 1, width = 1, height = 1, properties = { Professions = "burglar,janitor" } },
  { name = "", type = "SpawnPoint", x = 3427, y = 7167, z = 1, width = 1, height = 1, properties = { Professions = "officeworker,secretary" } },
  { name = "", type = "SpawnPoint", x = 3416, y = 7142, z = 1, width = 1, height = 1, properties = { Professions = "janitor" } },
  { name = "parkingstall", type = "ParkingStall", x = 3469, y = 7156, z = 0, width = 4, height = 18, properties = { Direction = "E" } },
  { name = "parkingstall", type = "ParkingStall", x = 3513, y = 7112, z = 0, width = 4, height = 12, properties = { Direction = "W" } },
  { name = "medium", type = "ParkingStall", x = 3510, y = 7162, z = 0, width = 9, height = 4, properties = { Direction = "S" } },
  { name = "parkingstall", type = "ParkingStall", x = 3457, y = 7067, z = 0, width = 4, height = 24, properties = { Direction = "W" } },
  { name = "good", type = "ParkingStall", x = 3465, y = 7071, z = 0, width = 3, height = 4, properties = { Direction = "N" } },
  { name = "police", type = "ParkingStall", x = 3494, y = 7069, z = 0, width = 3, height = 6, properties = { Direction = "S" } },
  { name = "ambulance", type = "ParkingStall", x = 3478, y = 7092, z = 0, width = 6, height = 3, properties = { Direction = "W" } },
  { name = "police", type = "ParkingStall", x = 3554, y = 6984, z = 0, width = 3, height = 8, properties = { Direction = "S" } },
  { name = "parkingstall", type = "ParkingStall", x = 3554, y = 7008, z = 0, width = 4, height = 12, properties = { Direction = "W" } },
  { name = "parkingstall", type = "ParkingStall", x = 3564, y = 7011, z = 0, width = 4, height = 9, properties = { Direction = "E" } },
  { name = "parkingstall", type = "ParkingStall", x = 3555, y = 7089, z = 0, width = 4, height = 27, properties = { Direction = "W" } },
  { name = "postal", type = "ParkingStall", x = 3586, y = 7104, z = 0, width = 4, height = 3, properties = { Direction = "W" } },
  { name = "parkingstall", type = "ParkingStall", x = 3555, y = 7183, z = 0, width = 25, height = 4, properties = { Direction = "S" } },
  { name = "trafficjamw", type = "ParkingStall", x = 3380, y = 7187, z = 0, width = 5, height = 4, properties = { Direction = "W" } },
  { name = "parkingstall", type = "ParkingStall", x = 3347, y = 7171, z = 0, width = 24, height = 4, properties = { Direction = "S" } },
  { name = "trafficjamn", type = "ParkingStall", x = 3377, y = 7191, z = 0, width = 6, height = 8, properties = { Direction = "N" } },
  { name = "parkingstall", type = "ParkingStall", x = 3563, y = 7172, z = 0, width = 18, height = 4, properties = { Direction = "N" } },
  { name = "trafficjams", type = "ParkingStall", x = 3374, y = 7181, z = 0, width = 6, height = 10, properties = { Direction = "S" } },
  { name = "parkingstall", type = "ParkingStall", x = 3459, y = 7138, z = 0, width = 4, height = 12, properties = { Direction = "W" } },
  { name = "parkingstall", type = "ParkingStall", x = 3452, y = 7156, z = 0, width = 4, height = 18, properties = { Direction = "E" } },
  { name = "parkingstall", type = "ParkingStall", x = 3438, y = 7133, z = 0, width = 4, height = 18, properties = { Direction = "W" } },
  { name = "parkingstall", type = "ParkingStall", x = 3387, y = 7134, z = 0, width = 4, height = 57, properties = { Direction = "E" } },
  { name = "parkingstall", type = "ParkingStall", x = 3347, y = 7131, z = 0, width = 4, height = 21, properties = { Direction = "W" } },
  { name = "parkingstall", type = "ParkingStall", x = 3365, y = 7132, z = 0, width = 4, height = 9, properties = { Direction = "W" } },
  { name = "parkingstall", type = "ParkingStall", x = 3358, y = 7142, z = 0, width = 4, height = 9, properties = { Direction = "E" } },
  { name = "parkingstall", type = "ParkingStall", x = 3359, y = 7124, z = 0, width = 18, height = 4, properties = { Direction = "S" } },
  { name = "parkingstall", type = "ParkingStall", x = 3407, y = 7113, z = 0, width = 52, height = 4, properties = { Direction = "N" } },
  { name = "parkingstall", type = "ParkingStall", x = 3358, y = 7113, z = 0, width = 33, height = 4, properties = { Direction = "N" } },
  { name = "parkingstall", type = "ParkingStall", x = 3400, y = 7127, z = 0, width = 36, height = 4, properties = { Direction = "S" } },
  { name = "parkingstall", type = "ParkingStall", x = 3470, y = 7113, z = 0, width = 4, height = 11, properties = { Direction = "E" } },
  { name = "parkingstall", type = "ParkingStall", x = 3412, y = 7196, z = 0, width = 15, height = 4, properties = { Direction = "N" } },
  { name = "trafficjame", type = "ParkingStall", x = 3536, y = 7132, z = 0, width = 6, height = 5, properties = { Direction = "E" } },
  { name = "trafficjamw", type = "ParkingStall", x = 3542, y = 7131, z = 0, width = 7, height = 5, properties = { Direction = "W" } },
  { name = "trafficjamn", type = "ParkingStall", x = 3542, y = 7136, z = 0, width = 4, height = 7, properties = { Direction = "N" } },
  { name = "trafficjams", type = "ParkingStall", x = 3539, y = 7125, z = 0, width = 5, height = 6, properties = { Direction = "S" } },
  { name = "parkingstall", type = "ParkingStall", x = 3559, y = 7157, z = 0, width = 4, height = 14, properties = { Direction = "E" } },
  { name = "", type = "SpawnPoint", x = 3579, y = 7161, z = 0, width = 1, height = 1, properties = { Professions = "drugdealer" } },
  { name = "", type = "SpawnPoint", x = 3577, y = 7150, z = 0, width = 1, height = 1, properties = { Professions = "doctor" } },
  { name = "", type = "SpawnPoint", x = 3487, y = 7165, z = 0, width = 1, height = 1, properties = { Professions = "shopclerk" } },
  { name = "", type = "SpawnPoint", x = 3567, y = 7149, z = 0, width = 1, height = 1, properties = { Professions = "shopclerk" } },
  { name = "", type = "SpawnPoint", x = 3574, y = 7093, z = 1, width = 1, height = 1, properties = { Professions = "itworker,officeworker" } },
  { name = "", type = "SpawnPoint", x = 3578, y = 7099, z = 1, width = 1, height = 1, properties = { Professions = "officeworker" } },
  { name = "", type = "SpawnPoint", x = 3574, y = 7096, z = 0, width = 1, height = 1, properties = { Professions = "secretary" } },
  { name = "postal", type = "ParkingStall", x = 3586, y = 7099, z = 0, width = 4, height = 3, properties = { Direction = "W" } },
  { name = "postal", type = "ParkingStall", x = 3586, y = 7094, z = 0, width = 4, height = 3, properties = { Direction = "W" } },
  { name = "postal", type = "ParkingStall", x = 3584, y = 7110, z = 0, width = 4, height = 3, properties = { Direction = "E" } },
  { name = "School", type = "", x = 3503, y = 6960, z = 0, width = 56, height = 63 },
  { name = "Playground", type = "", x = 3474, y = 7006, z = 0, width = 26, height = 17 },
  { name = "Suburban Houses x2", type = "", x = 3421, y = 6962, z = 0, width = 56, height = 20 },
  { name = "Low Wooden Fence", type = "", x = 3445, y = 6962, z = 0, width = 3, height = 23 },
  { name = "Low Chainlink Fence", type = "", x = 3507, y = 6960, z = 0, width = 5, height = 61 },
  { name = "ambulance", type = "ParkingStall", x = 3554, y = 6995, z = 0, width = 3, height = 8, properties = { Direction = "S" } },
  { name = "fire", type = "ParkingStall", x = 3560, y = 6977, z = 0, width = 8, height = 3, properties = { Direction = "W" } },
  { name = "parkingstall", type = "ParkingStall", x = 3476, y = 7099, z = 0, width = 4, height = 9, properties = { Direction = "W" } },
  { name = "parkingstall", type = "ParkingStall", x = 3486, y = 7099, z = 0, width = 4, height = 9, properties = { Direction = "E" } },
  { name = "parkingstall", type = "ParkingStall", x = 3490, y = 7099, z = 0, width = 4, height = 9, properties = { Direction = "W" } },
  { name = "bad", type = "ParkingStall", x = 3498, y = 7104, z = 0, width = 12, height = 4, properties = { Direction = "S" } },
  { name = "parkingstall", type = "ParkingStall", x = 3501, y = 7094, z = 0, width = 9, height = 4, properties = { Direction = "N" } },
  { name = "parkingstall", type = "ParkingStall", x = 3501, y = 7090, z = 0, width = 9, height = 4, properties = { Direction = "S" } },
  { name = "parkingstall", type = "ParkingStall", x = 3501, y = 7080, z = 0, width = 9, height = 4, properties = { Direction = "N" } },
  { name = "parkingstall", type = "ParkingStall", x = 3501, y = 7076, z = 0, width = 9, height = 4, properties = { Direction = "S" } },
  { name = "parkingstall", type = "ParkingStall", x = 3502, y = 7067, z = 0, width = 9, height = 4, properties = { Direction = "N" } },
  { name = "parkingstall", type = "ParkingStall", x = 3505, y = 7148, z = 0, width = 16, height = 4, properties = { Direction = "N" } },
  { name = "parkingstall", type = "ParkingStall", x = 3521, y = 7152, z = 0, width = 4, height = 11, properties = { Direction = "E" } },
  { name = "fire", type = "ParkingStall", x = 3485, y = 7092, z = 0, width = 8, height = 3, properties = { Direction = "W" } },
  { name = "", type = "SpawnPoint", x = 3488, y = 7157, z = 0, width = 1, height = 1, properties = { Professions = "shopclerk" } },
  { name = "", type = "SpawnPoint", x = 3494, y = 7166, z = 0, width = 1, height = 1, properties = { Professions = "cook" } },
  { name = "", type = "SpawnPoint", x = 3492, y = 7157, z = 0, width = 1, height = 1, properties = { Professions = "accountant" } },
  { name = "", type = "SpawnPoint", x = 3486, y = 7167, z = 1, width = 1, height = 1, properties = { Professions = "unemployed" } },
  { name = "", type = "SpawnPoint", x = 3490, y = 7156, z = 1, width = 1, height = 1, properties = { Professions = "fireofficer,unemployed" } },
  { name = "", type = "SpawnPoint", x = 3490, y = 7156, z = 2, width = 1, height = 1, properties = { Professions = "militaryofficer,unemployed" } },
  { name = "", type = "SpawnPoint", x = 3486, y = 7166, z = 2, width = 1, height = 1, properties = { Professions = "nurse,unemployed" } },
  { name = "", type = "SpawnPoint", x = 3500, y = 7161, z = 2, width = 1, height = 1, properties = { Professions = "drugdealer,unemployed" } },
  { name = "", type = "SpawnPoint", x = 3490, y = 7167, z = 3, width = 1, height = 1, properties = { Professions = "customerservice,unemployed" } },
  { name = "", type = "SpawnPoint", x = 3499, y = 7161, z = 3, width = 1, height = 1, properties = { Professions = "unemployed" } },
  { name = "", type = "SpawnPoint", x = 3490, y = 7156, z = 3, width = 1, height = 1, properties = { Professions = "unemployed" } },
  { name = "", type = "SpawnPoint", x = 3487, y = 7167, z = 4, width = 1, height = 1, properties = { Professions = "farmer,unemployed" } },
  { name = "", type = "SpawnPoint", x = 3499, y = 7156, z = 4, width = 1, height = 1, properties = { Professions = "burglar,unemployed" } },
  { name = "", type = "SpawnPoint", x = 3497, y = 7164, z = 5, width = 1, height = 1, properties = { Professions = "janitor,unemployed" } },
  { name = "", type = "SpawnPoint", x = 3475, y = 7078, z = 0, width = 1, height = 1, properties = { Professions = "cashier" } },
  { name = "", type = "SpawnPoint", x = 3476, y = 7070, z = 0, width = 1, height = 1, properties = { Professions = "unemployed" } },
  { name = "", type = "SpawnPoint", x = 3486, y = 7071, z = 0, width = 1, height = 1, properties = { Professions = "unemployed" } },
  { name = "", type = "SpawnPoint", x = 3476, y = 7074, z = 1, width = 1, height = 1, properties = { Professions = "unemployed" } },
  { name = "", type = "SpawnPoint", x = 3486, y = 7077, z = 1, width = 1, height = 1, properties = { Professions = "unemployed" } },
  { name = "", type = "SpawnPoint", x = 3481, y = 7083, z = 1, width = 1, height = 1, properties = { Professions = "unemployed" } },
  { name = "", type = "SpawnPoint", x = 3476, y = 7074, z = 2, width = 1, height = 1, properties = { Professions = "unemployed" } },
  { name = "", type = "SpawnPoint", x = 3487, y = 7079, z = 2, width = 1, height = 1, properties = { Professions = "teacher,unemployed" } },
  { name = "", type = "SpawnPoint", x = 3482, y = 7083, z = 2, width = 1, height = 1, properties = { Professions = "unemployed" } },
  { name = "", type = "SpawnPoint", x = 3476, y = 7071, z = 3, width = 1, height = 1, properties = { Professions = "itworker,unemployed" } },
  { name = "", type = "SpawnPoint", x = 3487, y = 7071, z = 3, width = 1, height = 1, properties = { Professions = "unemployed" } },
  { name = "", type = "SpawnPoint", x = 3482, y = 7083, z = 3, width = 1, height = 1, properties = { Professions = "unemployed" } },
  { name = "", type = "SpawnPoint", x = 3476, y = 7083, z = 4, width = 1, height = 1, properties = { Professions = "drugdealer,secretary" } },
  { name = "", type = "SpawnPoint", x = 3486, y = 7074, z = 4, width = 1, height = 1, properties = { Professions = "unemployed" } },
  { name = "", type = "SpawnPoint", x = 3476, y = 7072, z = 4, width = 1, height = 1, properties = { Professions = "truckdriver,unemployed" } },
  { name = "", type = "SpawnPoint", x = 3482, y = 7084, z = 5, width = 1, height = 1, properties = { Professions = "unemployed" } },
  { name = "", type = "SpawnPoint", x = 3486, y = 7074, z = 5, width = 1, height = 1, properties = { Professions = "unemployed" } },
  { name = "", type = "SpawnPoint", x = 3486, y = 7074, z = 6, width = 1, height = 1, properties = { Professions = "chef,unemployed" } },
  { name = "", type = "SpawnPoint", x = 3480, y = 7082, z = 6, width = 1, height = 1, properties = { Professions = "bookkeeper,unemployed" } },
  { name = "", type = "SpawnPoint", x = 3480, y = 7078, z = 7, width = 1, height = 1, properties = { Professions = "janitor,unemployed" } },
  { name = "PizzaWhirled", type = "ZombiesType", x = 3431, y = 7133, z = 0, width = 5, height = 17 },
  { name = "CoffeeShop", type = "ZombiesType", x = 3484, y = 7162, z = 0, width = 16, height = 9 },
  { name = "Gigamart", type = "ZombiesType", x = 3410, y = 7183, z = 0, width = 26, height = 11 },
  { name = "Police", type = "ZombiesType", x = 3424, y = 7165, z = 0, width = 6, height = 6 },
  { name = "Gigamart", type = "ZombiesType", x = 3410, y = 7174, z = 0, width = 10, height = 9 },
  { name = "Restaurant", type = "ZombiesType", x = 3420, y = 7174, z = 0, width = 16, height = 9 },
  { name = "School", type = "ZombiesType", x = 3502, y = 6955, z = 0, width = 74, height = 76 },
  { name = "Athletic", type = "", x = 3481, y = 7066, z = 0, width = 10, height = 16 },
  { name = "Construction", type = "ZombiesType", x = 3469, y = 6925, z = 0, width = 17, height = 19 },
  { name = "", type = "SpawnPoint", x = 3401, y = 7175, z = 1, width = 1, height = 1, properties = { Professions = "drugdealer" } },
  { name = "", type = "SpawnPoint", x = 3428, y = 7177, z = 1, width = 1, height = 1, properties = { Professions = "shopclerk" } },
  { name = "", type = "SpawnPoint", x = 3394, y = 7159, z = 0, width = 1, height = 1, properties = { Professions = "chef" } },
  { name = "", type = "SpawnPoint", x = 3361, y = 7184, z = 0, width = 1, height = 1, properties = { Professions = "janitor" } },
  { name = "parkingstall", type = "ParkingStall", x = 3527, y = 7112, z = 0, width = 4, height = 12, properties = { Direction = "E" } },
  { name = "parkingstall", type = "ParkingStall", x = 3470, y = 7182, z = 0, width = 4, height = 12, properties = { Direction = "E" } },
  { name = "parkingstall", type = "ParkingStall", x = 3456, y = 7192, z = 0, width = 12, height = 4, properties = { Direction = "S" } },
  { name = "bad", type = "ParkingStall", x = 3323, y = 6986, z = 0, width = 4, height = 3, properties = { Direction = "W" } },
  { name = "bad", type = "ParkingStall", x = 3319, y = 6948, z = 0, width = 4, height = 3, properties = { Direction = "W" } },
  { name = "medium", type = "ParkingStall", x = 3343, y = 6920, z = 0, width = 4, height = 3, properties = { Direction = "E" } },
  { name = "parkingstall", type = "ParkingStall", x = 3438, y = 7157, z = 0, width = 4, height = 36, properties = { Direction = "W" } },
  { name = "good", type = "ParkingStall", x = 3394, y = 7196, z = 0, width = 9, height = 4, properties = { Direction = "N" } },
  { name = "sports", type = "ParkingStall", x = 3452, y = 7138, z = 0, width = 4, height = 12, properties = { Direction = "E" } },
  { name = "bad", type = "ParkingStall", x = 3459, y = 7156, z = 0, width = 4, height = 18, properties = { Direction = "W" } },
  { name = "bad", type = "ParkingStall", x = 3469, y = 7137, z = 0, width = 4, height = 15, properties = { Direction = "E" } },
  { name = "parkingstall", type = "ParkingStall", x = 3565, y = 7098, z = 0, width = 4, height = 15, properties = { Direction = "E" } },
  { name = "police", type = "ParkingStall", x = 3565, y = 7092, z = 0, width = 3, height = 4, properties = { Direction = "S" } },
  { name = "postal", type = "ParkingStall", x = 3571, y = 7081, z = 0, width = 4, height = 3, properties = { Direction = "W" } },
  { name = "trafficjamn", type = "ParkingStall", x = 3403, y = 7034, z = 0, width = 3, height = 6, properties = { Direction = "N" } },
  { name = "trafficjame", type = "ParkingStall", x = 3397, y = 7033, z = 0, width = 6, height = 3, properties = { Direction = "E" } },
  { name = "trafficjamw", type = "ParkingStall", x = 3403, y = 7031, z = 0, width = 7, height = 3, properties = { Direction = "W" } },
  { name = "", type = "SpawnPoint", x = 3354, y = 7004, z = 1, width = 1, height = 1, properties = { Professions = "unemployed" } },
  { name = "", type = "SpawnPoint", x = 3320, y = 6960, z = 1, width = 1, height = 1, properties = { Professions = "unemployed" } },
  { name = "", type = "SpawnPoint", x = 3398, y = 6978, z = 1, width = 1, height = 1, properties = { Professions = "unemployed" } },
  { name = "", type = "SpawnPoint", x = 3520, y = 6997, z = 0, width = 1, height = 1, properties = { Professions = "teacher" } },
  { name = "police", type = "ParkingStall", x = 3436, y = 7032, z = 0, width = 4, height = 3, properties = { Direction = "E" } },
  { name = "trafficjame", type = "ParkingStall", x = 3443, y = 7032, z = 0, width = 5, height = 3, properties = { Direction = "E" } },
  { name = "trafficjamw", type = "ParkingStall", x = 3448, y = 7031, z = 0, width = 5, height = 3, properties = { Direction = "W" } },
  { name = "trafficjamn", type = "ParkingStall", x = 3541, y = 7037, z = 0, width = 5, height = 6, properties = { Direction = "N" } },
  { name = "trafficjame", type = "ParkingStall", x = 3536, y = 7034, z = 0, width = 5, height = 4, properties = { Direction = "E" } },
  { name = "trafficjamw", type = "ParkingStall", x = 3542, y = 7031, z = 0, width = 5, height = 4, properties = { Direction = "W" } },
  { name = "trafficjams", type = "ParkingStall", x = 3530, y = 7040, z = 0, width = 3, height = 4, properties = { Direction = "S" } },
  { name = "spiffo", type = "ParkingStall", x = 3491, y = 6962, z = 0, width = 4, height = 3, properties = { Direction = "E" } },
  { name = "", type = "TownZone", x = 3345, y = 7113, z = 0, width = 128, height = 87 },
  { name = "trafficjamw", type = "ParkingStall", x = 3708, y = 7027, z = 0, width = 6, height = 5 },
  { name = "ambulance", type = "ParkingStall", x = 3651, y = 7037, z = 0, width = 9, height = 3, properties = { Direction = "E" } },
  { name = "parkingstall", type = "ParkingStall", x = 3660, y = 7114, z = 0, width = 12, height = 4, properties = { Direction = "S" } },
  { name = "parkingstall", type = "ParkingStall", x = 3687, y = 7007, z = 0, width = 13, height = 4, properties = { Direction = "N" } },
  { name = "parkingstall", type = "ParkingStall", x = 3659, y = 7083, z = 0, width = 4, height = 21, properties = { Direction = "W" } },
  { name = "parkingstall", type = "ParkingStall", x = 3703, y = 6984, z = 0, width = 10, height = 4, properties = { Direction = "N" } },
  { name = "parkingstall", type = "ParkingStall", x = 3663, y = 7150, z = 0, width = 4, height = 26, properties = { Direction = "W" } },
  { name = "parkingstall", type = "ParkingStall", x = 3603, y = 7090, z = 0, width = 4, height = 25, properties = { Direction = "E" } },
  { name = "trafficjams", type = "ParkingStall", x = 3704, y = 7020, z = 0, width = 4, height = 8 },
  { name = "parkingstall", type = "ParkingStall", x = 3683, y = 7155, z = 0, width = 4, height = 20, properties = { Direction = "E" } },
  { name = "trafficjamn", type = "ParkingStall", x = 3704, y = 7028, z = 0, width = 4, height = 5 },
  { name = "parkingstall", type = "ParkingStall", x = 3687, y = 7175, z = 0, width = 13, height = 4, properties = { Direction = "N" } },
  { name = "parkingstall", type = "ParkingStall", x = 3684, y = 7016, z = 0, width = 17, height = 4, properties = { Direction = "S" } },
  { name = "parkingstall", type = "ParkingStall", x = 3720, y = 6995, z = 0, width = 8, height = 3, properties = { Direction = "E" } },
  { name = "parkingstall", type = "ParkingStall", x = 3719, y = 6989, z = 0, width = 8, height = 3, properties = { Direction = "W" } },
  { name = "parkingstall", type = "ParkingStall", x = 3644, y = 7077, z = 0, width = 4, height = 21, properties = { Direction = "W" } },
  { name = "parkingstall", type = "ParkingStall", x = 3668, y = 7077, z = 0, width = 4, height = 29, properties = { Direction = "E" } },
  { name = "police", type = "ParkingStall", x = 3721, y = 7133, z = 0, width = 3, height = 4, properties = { Direction = "N" } },
  { name = "police", type = "ParkingStall", x = 3731, y = 7127, z = 0, width = 3, height = 4, properties = { Direction = "S" } },
  { name = "police", type = "ParkingStall", x = 3698, y = 7133, z = 0, width = 3, height = 4, properties = { Direction = "N" } },
  { name = "police", type = "ParkingStall", x = 3705, y = 7125, z = 0, width = 3, height = 4, properties = { Direction = "S" } },
  { name = "normalburnt", type = "ParkingStall", x = 3694, y = 7097, z = 0, width = 4, height = 6, properties = { Direction = "E" } },
  { name = "Army", type = "ZombiesType", x = 3683, y = 7045, z = 0, width = 92, height = 105 },
  { name = "Dinner", type = "ZombiesType", x = 3682, y = 7150, z = 0, width = 21, height = 33 },
  { name = "parkingstall", type = "ParkingStall", x = 3645, y = 6995, z = 0, width = 9, height = 4, properties = { Direction = "N" } },
  { name = "TrailerPark", type = "ZombiesType", x = 3601, y = 6957, z = 0, width = 81, height = 66 },
  { name = "Gas2Go", type = "ZombiesType", x = 3714, y = 6983, z = 0, width = 25, height = 39 },
  { name = "bad", type = "ParkingStall", x = 3607, y = 6978, z = 0, width = 4, height = 3, properties = { Direction = "W" } },
  { name = "parkingstall", type = "ParkingStall", x = 3607, y = 6986, z = 0, width = 6, height = 4, properties = { Direction = "S" } },
  { name = "bad", type = "ParkingStall", x = 3603, y = 6982, z = 0, width = 4, height = 3, properties = { Direction = "W" } },
  { name = "medium", type = "ParkingStall", x = 3661, y = 6998, z = 0, width = 3, height = 4, properties = { Direction = "N" } },
  { name = "", type = "SpawnPoint", x = 3699, y = 7084, z = 1, width = 1, height = 1, properties = { Professions = "militaryofficer,militarysoldier" } },
  { name = "", type = "SpawnPoint", x = 3727, y = 7006, z = 0, width = 1, height = 1, properties = { Professions = "shopclerk,truckdriver" } },
  { name = "", type = "SpawnPoint", x = 3609, y = 6997, z = 0, width = 1, height = 1, properties = { Professions = "unemployed" } },
  { name = "trafficjame", type = "ParkingStall", x = 3741, y = 7035, z = 0, width = 9, height = 4, properties = { Direction = "E" } },
  { name = "trafficjams", type = "ParkingStall", x = 3747, y = 7027, z = 0, width = 5, height = 8, properties = { Direction = "S" } },
  { name = "trafficjamn", type = "ParkingStall", x = 3750, y = 7035, z = 0, width = 5, height = 8, properties = { Direction = "N" } },
  { name = "Forest", type = "ZoneStory", x = 3872, y = 7033, z = 0, width = 15, height = 12 },
  { name = "Forest", type = "ZoneStory", x = 3867, y = 6911, z = 0, width = 12, height = 9 },
  { name = "Lake", type = "ZoneStory", x = 3813, y = 7066, z = 0, width = 11, height = 10 },
  { name = "Lake", type = "ZoneStory", x = 3810, y = 7001, z = 0, width = 7, height = 14 },
  { name = "Lake", type = "ZoneStory", x = 3810, y = 7031, z = 0, width = 7, height = 12 },
  { name = "Lake", type = "ZoneStory", x = 3807, y = 7102, z = 0, width = 9, height = 11 },
  { name = "parkingstall", type = "ParkingStall", x = 3655, y = 7083, z = 0, width = 4, height = 21, properties = { Direction = "E" } },
  { name = "", type = "SpawnPoint", x = 3704, y = 7069, z = 0, width = 1, height = 1, properties = { Professions = "constructionworker" } },
  { name = "medium", type = "ParkingStall", x = 3799, y = 7098, z = 0, width = 3, height = 4, properties = { Direction = "S" } },
  { name = "ranger", type = "ParkingStall", x = 3810, y = 6989, z = 0, width = 4, height = 3, properties = { Direction = "E" } },
  { name = "ambulance", type = "ParkingStall", x = 3745, y = 7021, z = 0, width = 4, height = 3, properties = { Direction = "W" } },
  { name = "normalburnt", type = "ParkingStall", x = 3716, y = 7063, z = 0, width = 4, height = 9, properties = { Direction = "E" } },
  { name = "trafficjamw", type = "ParkingStall", x = 3624, y = 7128, z = 0, width = 6, height = 3, properties = { Direction = "W" } },
  { name = "trafficjams", type = "ParkingStall", x = 3625, y = 7123, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "TrailerPark", x = 3602, y = 6958, z = 0, width = 78, height = 62 },
  { name = "", type = "TownZone", x = 3657, y = 7150, z = 0, width = 40, height = 34 },
  { name = "ranger", type = "ParkingStall", x = 3142, y = 7290, z = 0, width = 6, height = 4, properties = { Direction = "S" } },
  { name = "parkingstall", type = "ParkingStall", x = 3243, y = 7251, z = 0, width = 3, height = 8, properties = { Direction = "S" } },
  { name = "trafficjams", type = "ParkingStall", x = 3294, y = 7228, z = 0, width = 5, height = 6, properties = { Direction = "S" } },
  { name = "trafficjame", type = "ParkingStall", x = 3292, y = 7234, z = 0, width = 7, height = 4, properties = { Direction = "E" } },
  { name = "bad", type = "ParkingStall", x = 3271, y = 7238, z = 0, width = 4, height = 3, properties = { Direction = "E" } },
  { name = "medium", type = "ParkingStall", x = 3186, y = 7216, z = 0, width = 3, height = 4, properties = { Direction = "N" } },
  { name = "", type = "SpawnPoint", x = 3173, y = 7291, z = 0, width = 1, height = 1, properties = { Professions = "unemployed" } },
  { name = "", type = "SpawnPoint", x = 3172, y = 7267, z = 0, width = 1, height = 1, properties = { Professions = "unemployed" } },
  { name = "ConstructionSite", type = "ZombiesType", x = 3313, y = 7195, z = 0, width = 44, height = 49 },
  { name = "Church", type = "ZombiesType", x = 3386, y = 7259, z = 0, width = 49, height = 54 },
  { name = "", type = "SpawnPoint", x = 3114, y = 7224, z = 0, width = 1, height = 1, properties = { Professions = "farmer" } },
  { name = "", type = "SpawnPoint", x = 3082, y = 7244, z = 0, width = 1, height = 1, properties = { Professions = "farmer" } },
  { name = "ranger", type = "ParkingStall", x = 3048, y = 7242, z = 0, width = 4, height = 3, properties = { Direction = "W" } },
  { name = "", type = "SpawnPoint", x = 3014, y = 7216, z = 0, width = 1, height = 1, properties = { Professions = "parkranger" } },
  { name = "bad", type = "ParkingStall", x = 3269, y = 7291, z = 0, width = 4, height = 18, properties = { Direction = "W" } },
  { name = "bad", type = "ParkingStall", x = 3251, y = 7309, z = 0, width = 18, height = 4, properties = { Direction = "N" } },
  { name = "", type = "SpawnPoint", x = 3251, y = 7299, z = 1, width = 1, height = 1, properties = { Professions = "burglar,drugdealer,unemployed" } },
  { name = "", type = "SpawnPoint", x = 3254, y = 7292, z = 1, width = 1, height = 1, properties = { Professions = "unemployed" } },
  { name = "bad", type = "ParkingStall", x = 3154, y = 7229, z = 0, width = 19, height = 4, properties = { Direction = "N" } },
  { name = "medium", type = "ParkingStall", x = 3251, y = 7214, z = 0, width = 4, height = 3, properties = { Direction = "W" } },
  { name = "", type = "FarmLand", x = 3051, y = 7226, z = 0, width = 52, height = 37 },
  { name = "", type = "TownZone", z = 0, geometry = "polygon", points = { 3096, 7225, 3095, 7201, 3141, 7200, 3192, 7200, 3291, 7200, 3300, 7200, 3300, 7338, 3287, 7339, 3240, 7315, 3215, 7298, 3209, 7278, 3195, 7282, 3188, 7296, 3165, 7300, 3140, 7294, 3138, 7250, 3107, 7242 } },
  { name = "", type = "SpawnPoint", x = 3208, y = 7212, z = 1, width = 1, height = 1, properties = { Professions = "unemployed" } },
  { name = "", type = "SpawnPoint", x = 3201, y = 7260, z = 0, width = 1, height = 1, properties = { Professions = "unemployed" } },
  { name = "", type = "SpawnPoint", x = 3236, y = 7255, z = 0, width = 1, height = 1, properties = { Professions = "unemployed" } },
  { name = "Forest", type = "ZoneStory", x = 3129, y = 7381, z = 0, width = 16, height = 11 },
  { name = "Forest", type = "ZoneStory", x = 3167, y = 7407, z = 0, width = 8, height = 9 },
  { name = "Lake", type = "ZoneStory", x = 3073, y = 7301, z = 0, width = 8, height = 9 },
  { name = "Forest", type = "ZoneStory", x = 3018, y = 7418, z = 0, width = 11, height = 12 },
  { name = "Bunker + Dock", type = "", x = 3210, y = 7415, z = 0, width = 47, height = 38 },
  { name = "medium", type = "ParkingStall", x = 3206, y = 7342, z = 0, width = 4, height = 12, properties = { Direction = "W" } },
  { name = "bad", type = "ParkingStall", x = 3202, y = 7311, z = 0, width = 15, height = 4, properties = { Direction = "N" } },
  { name = "Army", type = "ZombiesType", x = 3222, y = 7362, z = 0, width = 35, height = 31 },
  { name = "parkingstall", type = "ParkingStall", x = 3224, y = 7329, z = 0, width = 4, height = 27, properties = { Direction = "E" } },
  { name = "radio", type = "ParkingStall", x = 3204, y = 7322, z = 0, width = 9, height = 4, properties = { Direction = "S" } },
  { name = "ranger", type = "ParkingStall", x = 3011, y = 7209, z = 0, width = 3, height = 4, properties = { Direction = "N" } },
  { name = "", type = "Farm", x = 3051, y = 7226, z = 0, width = 53, height = 35 },
  { name = "sheep", type = "Ranch", x = 3111, y = 7266, z = 0, width = 20, height = 23 },
  { name = "sheep", type = "Ranch", x = 3116, y = 7254, z = 0, width = 12, height = 12 },
  { name = "parkingstall", type = "ParkingStall", x = 3487, y = 7263, z = 0, width = 15, height = 4, properties = { Direction = "N" } },
  { name = "parkingstall", type = "ParkingStall", x = 3335, y = 7228, z = 0, width = 12, height = 4, properties = { Direction = "S" } },
  { name = "parkingstall", type = "ParkingStall", x = 3409, y = 7217, z = 0, width = 30, height = 4, properties = { Direction = "N" } },
  { name = "bad", type = "ParkingStall", x = 3452, y = 7200, z = 0, width = 4, height = 30, properties = { Direction = "E" } },
  { name = "bad", type = "ParkingStall", x = 3366, y = 7228, z = 0, width = 39, height = 4, properties = { Direction = "S" } },
  { name = "parkingstall", type = "ParkingStall", x = 3409, y = 7210, z = 0, width = 30, height = 4, properties = { Direction = "S" } },
  { name = "parkingstall", type = "ParkingStall", x = 3472, y = 7263, z = 0, width = 11, height = 4, properties = { Direction = "N" } },
  { name = "medium", type = "ParkingStall", x = 3468, y = 7360, z = 0, width = 3, height = 4, properties = { Direction = "N" } },
  { name = "medium", type = "ParkingStall", x = 3459, y = 7366, z = 0, width = 3, height = 4, properties = { Direction = "N" } },
  { name = "medium", type = "ParkingStall", x = 3442, y = 7359, z = 0, width = 3, height = 4, properties = { Direction = "N" } },
  { name = "parkingstall", type = "ParkingStall", x = 3595, y = 7238, z = 0, width = 4, height = 21, properties = { Direction = "W" } },
  { name = "parkingstall", type = "ParkingStall", x = 3551, y = 7231, z = 0, width = 4, height = 27, properties = { Direction = "W" } },
  { name = "parkingstall", type = "ParkingStall", x = 3565, y = 7238, z = 0, width = 4, height = 21, properties = { Direction = "E" } },
  { name = "trafficjame", type = "ParkingStall", x = 3621, y = 7201, z = 0, width = 6, height = 4, properties = { Direction = "E" } },
  { name = "trafficjams", type = "ParkingStall", x = 3625, y = 7193, z = 0, width = 3, height = 8, properties = { Direction = "S" } },
  { name = "trafficjamw", type = "ParkingStall", x = 3628, y = 7197, z = 0, width = 8, height = 4, properties = { Direction = "W" } },
  { name = "trafficjamn", type = "ParkingStall", x = 3627, y = 7201, z = 0, width = 5, height = 7, properties = { Direction = "N" } },
  { name = "ambulance", type = "ParkingStall", x = 3594, y = 7213, z = 0, width = 4, height = 8, properties = { Direction = "S" } },
  { name = "fire", type = "ParkingStall", x = 3567, y = 7224, z = 0, width = 4, height = 6, properties = { Direction = "S" } },
  { name = "bad", type = "ParkingStall", x = 3366, y = 7211, z = 0, width = 9, height = 4, properties = { Direction = "W" } },
  { name = "bad", type = "ParkingStall", x = 3366, y = 7218, z = 0, width = 9, height = 4, properties = { Direction = "E" } },
  { name = "Suburban Idyll x3", type = "", x = 3484, y = 7385, z = 0, width = 76, height = 104 },
  { name = "parkingstall", type = "ParkingStall", x = 3440, y = 7272, z = 0, width = 4, height = 24, properties = { Direction = "W" } },
  { name = "parkingstall", type = "ParkingStall", x = 3453, y = 7281, z = 0, width = 4, height = 15, properties = { Direction = "E" } },
  { name = "parkingstall", type = "ParkingStall", x = 3445, y = 7263, z = 0, width = 11, height = 4, properties = { Direction = "N" } },
  { name = "", type = "SpawnPoint", x = 3324, y = 7226, z = 0, width = 1, height = 1, properties = { Professions = "officeworker" } },
  { name = "", type = "SpawnPoint", x = 3329, y = 7218, z = 0, width = 1, height = 1, properties = { Professions = "constructionworker" } },
  { name = "", type = "SpawnPoint", x = 3329, y = 7218, z = 1, width = 1, height = 1, properties = { Professions = "constructionworker" } },
  { name = "", type = "SpawnPoint", x = 3328, y = 7218, z = 3, width = 1, height = 1, properties = { Professions = "constructionworker" } },
  { name = "", type = "SpawnPoint", x = 3335, y = 7208, z = 3, width = 1, height = 1, properties = { Professions = "constructionworker" } },
  { name = "", type = "SpawnPoint", x = 3336, y = 7216, z = 5, width = 1, height = 1,
    properties = {
      Professions = "constructionworker,policeofficer,unemployed"
    }
  },
  { name = "", type = "SpawnPoint", x = 3331, y = 7219, z = 4, width = 1, height = 1, properties = { Professions = "drugdealer,unemployed" } },
  { name = "", type = "SpawnPoint", x = 3333, y = 7209, z = 4, width = 1, height = 1,
    properties = {
      Professions = "drugdealer,policeofficer,unemployed"
    }
  },
  { name = "Survivalist", type = "ZombiesType", x = 3406, y = 7265, z = 1, width = 4, height = 7 },
  { name = "good", type = "ParkingStall", x = 3590, y = 7284, z = 0, width = 4, height = 9, properties = { Direction = "E" } },
  { name = "sport", type = "ParkingStall", x = 3561, y = 7286, z = 0, width = 4, height = 3, properties = { Direction = "W" } },
  { name = "CountryClub", type = "ZombiesType", x = 3279, y = 7333, z = 0, width = 95, height = 88 },
  { name = "parkingstall", type = "ParkingStall", x = 3354, y = 7357, z = 0, width = 12, height = 4, properties = { Direction = "N" } },
  { name = "parkingstall", type = "ParkingStall", x = 3350, y = 7372, z = 0, width = 16, height = 4, properties = { Direction = "S" } },
  { name = "police", type = "ParkingStall", x = 3344, y = 7359, z = 0, width = 3, height = 4, properties = { Direction = "W" } },
  { name = "fire", type = "ParkingStall", x = 3322, y = 7336, z = 0, width = 8, height = 3, properties = { Direction = "E" } },
  { name = "", type = "SpawnPoint", x = 3473, y = 7256, z = 0, width = 1, height = 1, properties = { Professions = "unemployed" } },
  { name = "", type = "SpawnPoint", x = 3411, y = 7282, z = 0, width = 1, height = 1, properties = { Professions = "bookkeeper,securityguard" } },
  { name = "", type = "SpawnPoint", x = 3409, y = 7268, z = 0, width = 1, height = 1, properties = { Professions = "doctor" } },
  { name = "", type = "SpawnPoint", x = 3412, y = 7290, z = 1, width = 1, height = 1, properties = { Professions = "bookkeeper" } },
  { name = "", type = "SpawnPoint", x = 3405, y = 7281, z = 1, width = 1, height = 1, properties = { Professions = "nurse" } },
  { name = "bad", type = "ParkingStall", x = 3508, y = 7284, z = 0, width = 6, height = 4, properties = { Direction = "S" } },
  { name = "bad", type = "ParkingStall", x = 3487, y = 7291, z = 0, width = 4, height = 6, properties = { Direction = "E" } },
  { name = "", type = "SpawnPoint", x = 3452, y = 7340, z = 0, width = 1, height = 1, properties = { Professions = "burglar" } },
  { name = "", type = "SpawnPoint", x = 3455, y = 7355, z = 0, width = 1, height = 1, properties = { Professions = "unemployed" } },
  { name = "", type = "SpawnPoint", x = 3570, y = 7305, z = 2, width = 1, height = 1, properties = { Professions = "accountant,bookkeeper" } },
  { name = "", type = "SpawnPoint", x = 3583, y = 7299, z = 2, width = 1, height = 1, properties = { Professions = "unemployed" } },
  { name = "", type = "SpawnPoint", x = 3583, y = 7306, z = 0, width = 1, height = 1, properties = { Professions = "chef" } },
  { name = "", type = "SpawnPoint", x = 3580, y = 7214, z = 6, width = 1, height = 1, properties = { Professions = "cook" } },
  { name = "", type = "SpawnPoint", x = 3587, y = 7220, z = 6, width = 1, height = 1, properties = { Professions = "salesperson" } },
  { name = "", type = "SpawnPoint", x = 3575, y = 7224, z = 3, width = 1, height = 1, properties = { Professions = "unemployed" } },
  { name = "", type = "SpawnPoint", x = 3587, y = 7215, z = 2, width = 1, height = 1, properties = { Professions = "unemployed" } },
  { name = "", type = "SpawnPoint", x = 3575, y = 7222, z = 0, width = 1, height = 1, properties = { Professions = "shopclerk" } },
  { name = "", type = "SpawnPoint", x = 3162, y = 7216, z = 0, width = 1, height = 1, properties = { Professions = "unemployed" } },
  { name = "", type = "SpawnPoint", x = 3242, y = 7211, z = 1, width = 1, height = 1, properties = { Professions = "unemployed" } },
  { name = "", type = "SpawnPoint", x = 3494, y = 7288, z = 1, width = 1, height = 1, properties = { Professions = "officeworker" } },
  { name = "", type = "SpawnPoint", x = 3493, y = 7295, z = 0, width = 1, height = 1,
    properties = {
      Professions = "burglar,securityguard,shopclerk,truckdriver"
    }
  },
  { name = "Lake", type = "ZoneStory", x = 3391, y = 7430, z = 0, width = 15, height = 11 },
  { name = "Lake", type = "ZoneStory", x = 3433, y = 7466, z = 0, width = 8, height = 11 },
  { name = "Lake", type = "ZoneStory", x = 3343, y = 7454, z = 0, width = 12, height = 8 },
  { name = "Lake", type = "ZoneStory", x = 3309, y = 7458, z = 0, width = 10, height = 7 },
  { name = "bad", type = "ParkingStall", x = 3411, y = 7228, z = 0, width = 39, height = 4, properties = { Direction = "S" } },
  { name = "police", type = "ParkingStall", x = 3587, y = 7205, z = 0, width = 3, height = 4, properties = { Direction = "S" } },
  { name = "parkingstall", type = "ParkingStall", x = 3572, y = 7205, z = 0, width = 4, height = 3, properties = { Direction = "E" } },
  { name = "parkingstall", type = "ParkingStall", x = 3576, y = 7205, z = 0, width = 4, height = 3, properties = { Direction = "W" } },
  { name = "ambulance", type = "ParkingStall", x = 3433, y = 7263, z = 0, width = 6, height = 3, properties = { Direction = "W" } },
  { name = "parkingstall", type = "ParkingStall", x = 3394, y = 7217, z = 0, width = 9, height = 4, properties = { Direction = "N" } },
  { name = "parkingstall", type = "ParkingStall", x = 3394, y = 7210, z = 0, width = 9, height = 4, properties = { Direction = "S" } },
  { name = "bad", type = "ParkingStall", x = 3574, y = 7388, z = 0, width = 3, height = 4, properties = { Direction = "S" } },
  { name = "medium", type = "ParkingStall", x = 3462, y = 7405, z = 0, width = 4, height = 3, properties = { Direction = "E" } },
  { name = "bad", type = "ParkingStall", x = 3450, y = 7401, z = 0, width = 4, height = 3, properties = { Direction = "W" } },
  { name = "pig", type = "Ranch", x = 3407, y = 7397, z = 0, width = 12, height = 12 },
  { name = "cow", type = "Ranch", x = 3379, y = 7389, z = 0, width = 28, height = 18 },
  { name = "sheep", type = "Ranch", x = 3379, y = 7373, z = 0, width = 12, height = 16 },
  { name = "cow", type = "Ranch", x = 3379, y = 7353, z = 0, width = 16, height = 12 },
  { name = "bad", type = "ParkingStall", x = 3410, y = 7411, z = 0, width = 4, height = 9, properties = { Direction = "W" } },
  { name = "parkingstall", type = "ParkingStall", x = 3410, y = 7374, z = 0, width = 4, height = 3, properties = { Direction = "W" } },
  { name = "junkyard", type = "ParkingStall", x = 3404, y = 7410, z = 0, width = 4, height = 9, properties = { Direction = "W" } },
  { name = "junkyard", type = "ParkingStall", x = 3391, y = 7410, z = 0, width = 9, height = 4, properties = { Direction = "S" } },
  { name = "", type = "TownZone", x = 3359, y = 7200, z = 0, width = 105, height = 37 },
  { name = "", type = "TownZone", x = 3464, y = 7206, z = 0, width = 136, height = 76 },
  { name = "parkingstall", type = "ParkingStall", x = 3687, y = 7236, z = 0, width = 4, height = 9, properties = { Direction = "E" } },
  { name = "bad", type = "ParkingStall", x = 3696, y = 7220, z = 0, width = 9, height = 4, properties = { Direction = "N" } },
  { name = "bad", type = "ParkingStall", x = 3681, y = 7204, z = 0, width = 4, height = 3, properties = { Direction = "E" } },
  { name = "bad", type = "ParkingStall", x = 3697, y = 7204, z = 0, width = 4, height = 3, properties = { Direction = "W" } },
  { name = "medium", type = "ParkingStall", x = 3649, y = 7226, z = 0, width = 15, height = 4, properties = { Direction = "S" } },
  { name = "good", type = "ParkingStall", x = 3688, y = 7204, z = 0, width = 4, height = 3, properties = { Direction = "E" } },
  { name = "medium", type = "ParkingStall", x = 3659, y = 7207, z = 0, width = 4, height = 12, properties = { Direction = "W" } },
  { name = "parkingstall", type = "ParkingStall", x = 3664, y = 7230, z = 0, width = 4, height = 15, properties = { Direction = "W" } },
  { name = "bad", type = "ParkingStall", x = 3691, y = 7231, z = 0, width = 21, height = 4, properties = { Direction = "S" } },
  { name = "parkingstall", type = "ParkingStall", x = 3671, y = 7208, z = 0, width = 4, height = 18, properties = { Direction = "E" } },
  { name = "medium", type = "ParkingStall", x = 3705, y = 7210, z = 0, width = 4, height = 3, properties = { Direction = "W" } },
  { name = "parkingstall", type = "ParkingStall", x = 3655, y = 7207, z = 0, width = 4, height = 12, properties = { Direction = "E" } },
  { name = "parkingstall", type = "ParkingStall", x = 3645, y = 7206, z = 0, width = 4, height = 9, properties = { Direction = "W" } },
  { name = "parkingstall", type = "ParkingStall", x = 3642, y = 7215, z = 0, width = 6, height = 4, properties = { Direction = "N" } },
  { name = "CarRepair", type = "ZombiesType", x = 3673, y = 7200, z = 0, width = 41, height = 31 },
  { name = "VariousFoodMarket", type = "ZombiesType", x = 3647, y = 7226, z = 0, width = 21, height = 23 },
  { name = "Forest", type = "ZoneStory", x = 3868, y = 7353, z = 0, width = 14, height = 11 },
  { name = "Forest", type = "ZoneStory", x = 3878, y = 7204, z = 0, width = 11, height = 11 },
  { name = "Forest", type = "ZoneStory", x = 3869, y = 7459, z = 0, width = 12, height = 10 },
  { name = "parkingstall", type = "ParkingStall", x = 3615, y = 7216, z = 0, width = 4, height = 42, properties = { Direction = "E" } },
  { name = "Large Old Cemetary", type = "", x = 3765, y = 7296, z = 0, width = 71, height = 112 },
  { name = "Old Gas", type = "", x = 3681, y = 7279, z = 0, width = 65, height = 37 },
  { name = "Back Lane", type = "", x = 3667, y = 7279, z = 0, width = 12, height = 98 },
  { name = "good", type = "ParkingStall", x = 3712, y = 7347, z = 0, width = 15, height = 4, properties = { Direction = "N" } },
  { name = "parkingstall", type = "ParkingStall", x = 3687, y = 7363, z = 0, width = 21, height = 4, properties = { Direction = "N" } },
  { name = "parkingstall", type = "ParkingStall", x = 3721, y = 7359, z = 0, width = 15, height = 4, properties = { Direction = "S" } },
  { name = "medium", type = "ParkingStall", x = 3708, y = 7351, z = 0, width = 4, height = 12, properties = { Direction = "W" } },
  { name = "", type = "SpawnPoint", x = 3689, y = 7349, z = 1, width = 1, height = 1, properties = { Professions = "unemployed" } },
  { name = "", type = "SpawnPoint", x = 3716, y = 7331, z = 1, width = 1, height = 1,
    properties = {
      Professions = "drugdealer,truckdriver,unemployed"
    }
  },
  { name = "", type = "SpawnPoint", x = 3688, y = 7337, z = 0, width = 1, height = 1,
    properties = {
      Professions = "accountant,customerservice,officeworker,salesperson"
    }
  },
  { name = "", type = "SpawnPoint", x = 3656, y = 7238, z = 0, width = 1, height = 1, properties = { Professions = "cashier,shopclerk" } },
  { name = "", type = "SpawnPoint", x = 3686, y = 7213, z = 0, width = 1, height = 1, properties = { Professions = "burglar" } },
  { name = "", type = "SpawnPoint", x = 3645, y = 7241, z = 0, width = 1, height = 1, properties = { Professions = "unemployed" } },
  { name = "", type = "SpawnPoint", x = 3690, y = 7330, z = 0, width = 1, height = 1, properties = { Professions = "securityguard" } },
  { name = "", type = "SpawnPoint", x = 3708, y = 7329, z = 0, width = 1, height = 1, properties = { Professions = "chef,cook,waiter" } },
  { name = "", type = "SpawnPoint", x = 3699, y = 7351, z = 0, width = 1, height = 1,
    properties = {
      Professions = "bookkeeper,officeworker,secretary"
    }
  },
  { name = "", type = "SpawnPoint", x = 3685, y = 7369, z = 0, width = 1, height = 1, properties = { Professions = "drugdealer,unemployed" } },
  { name = "", type = "SpawnPoint", x = 3614, y = 7400, z = 0, width = 1, height = 1, properties = { Professions = "farmer,unemployed" } },
  { name = "", type = "SpawnPoint", x = 3688, y = 7356, z = 0, width = 1, height = 1, properties = { Professions = "unemployed" } },
  { name = "", type = "SpawnPoint", x = 3702, y = 7342, z = 0, width = 1, height = 1, properties = { Professions = "unemployed" } },
  { name = "police", type = "ParkingStall", x = 3666, y = 7315, z = 0, width = 3, height = 4, properties = { Direction = "S" } },
  { name = "bad", type = "ParkingStall", x = 3763, y = 7461, z = 0, width = 3, height = 4, properties = { Direction = "N" } },
  { name = "sport", type = "ParkingStall", x = 3667, y = 7328, z = 0, width = 3, height = 4, properties = { Direction = "S" } },
  { name = "", type = "TownZone", x = 3600, y = 7200, z = 0, width = 113, height = 49 },
  { name = "junkyard", type = "", x = 3816, y = 7226, z = 0, width = 51, height = 66 },
  { name = "pig", type = "Ranch", x = 3798, y = 7232, z = 0, width = 13, height = 15 },
  { name = "cow", type = "Ranch", x = 3802, y = 7207, z = 0, width = 9, height = 8 },
  { name = "", type = "SpawnPoint", x = 3805, y = 7226, z = 0, width = 1, height = 1, properties = { Professions = "farmer,unemployed,rancher" } },
  { name = "parkingstall", type = "ParkingStall", x = 3777, y = 7251, z = 0, width = 4, height = 15, properties = { Direction = "W" } },
  { name = "bad", type = "ParkingStall", x = 3810, y = 7251, z = 0, width = 4, height = 15, properties = { Direction = "E" } },
  { name = "junkyard", type = "ParkingStall", x = 3825, y = 7243, z = 0, width = 4, height = 18, properties = { Direction = "W" } },
  { name = "junkyard", type = "ParkingStall", x = 3830, y = 7227, z = 0, width = 15, height = 4, properties = { Direction = "N" } },
  { name = "junkyard", type = "ParkingStall", x = 3836, y = 7244, z = 0, width = 15, height = 4, properties = { Direction = "S" } },
  { name = "junkyard", type = "ParkingStall", x = 3830, y = 7258, z = 0, width = 10, height = 4, properties = { Direction = "S" } },
  { name = "junkyard", type = "ParkingStall", x = 3861, y = 7228, z = 0, width = 4, height = 15, properties = { Direction = "E" } },
  { name = "junkyard", type = "ParkingStall", x = 3849, y = 7235, z = 0, width = 4, height = 9, properties = { Direction = "E" } },
  { name = "junkyard", type = "ParkingStall", x = 3829, y = 7235, z = 0, width = 15, height = 4, properties = { Direction = "N" } },
  { name = "bad", type = "ParkingStall", x = 3847, y = 7257, z = 0, width = 12, height = 4, properties = { Direction = "S" } },
  { name = "parkingstall", type = "ParkingStall", x = 3827, y = 7288, z = 0, width = 18, height = 4, properties = { Direction = "S" } },
  { name = "junkyard", type = "ParkingStall", x = 3825, y = 7228, z = 0, width = 4, height = 15, properties = { Direction = "W" } },
  { name = "junkyard", type = "ParkingStall", x = 3845, y = 7227, z = 0, width = 15, height = 4, properties = { Direction = "N" } },
  { name = "junkyard", type = "ParkingStall", x = 3861, y = 7244, z = 0, width = 4, height = 15, properties = { Direction = "E" } }
}
