-- THIS FILE WAS AUTOMATICALLY GENERATED BY TileZed
local overlayMap = {}
overlayMap.VERSION = 1
overlayMap["Ekron02_8"] = {{ name = "other", tiles = {"Ekron02_0", "Ekron02_0"} }}
overlayMap["Ekron02_24"] = {{ name = "other", tiles = {"Ekron02_25", "Ekron02_25"} }}

if not TILEZED then
	getContainerOverlays():addOverlays(overlayMap)
end

return overlayMap
