-- THIS FILE WAS AUTOMATICALLY GENERATED BY TileZed
local overlayMap = {}
overlayMap.VERSION = 1
overlayMap["melos_tiles_appliances_01_0"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_32", "appliances_01_34", "appliances_01_36", "appliances_01_38"} }}
overlayMap["melos_tiles_appliances_01_1"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_25", "appliances_01_35", "appliances_01_37", "appliances_01_39"} }}
overlayMap["melos_tiles_appliances_01_2"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_43"} }}
overlayMap["melos_tiles_appliances_01_4"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_32", "appliances_01_34", "appliances_01_36", "appliances_01_38"} }}
overlayMap["melos_tiles_appliances_01_5"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_25", "appliances_01_35", "appliances_01_37", "appliances_01_39"} }}
overlayMap["melos_tiles_appliances_01_6"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_43"} }}
overlayMap["melos_tiles_appliances_01_7"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_42"} }}
overlayMap["melos_tiles_appliances_01_8"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_32", "appliances_01_34", "appliances_01_36", "appliances_01_38"} }}
overlayMap["melos_tiles_appliances_01_9"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_25", "appliances_01_35", "appliances_01_37", "appliances_01_39"} }}
overlayMap["melos_tiles_appliances_01_10"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_43"} }}
overlayMap["melos_tiles_appliances_01_11"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_42"} }}
overlayMap["melos_tiles_appliances_01_12"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_32", "appliances_01_34", "appliances_01_36", "appliances_01_38"} }}
overlayMap["melos_tiles_appliances_01_13"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_25", "appliances_01_35", "appliances_01_37", "appliances_01_39"} }}
overlayMap["melos_tiles_appliances_01_14"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_43"} }}
overlayMap["melos_tiles_appliances_01_15"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_42"} }}
overlayMap["melos_tiles_appliances_01_16"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_32", "appliances_01_38", "appliances_01_37"} }}
overlayMap["melos_tiles_appliances_01_17"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_25", "appliances_01_35", "appliances_01_37", "appliances_01_39"} }}
overlayMap["melos_tiles_appliances_01_18"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_43"} }}
overlayMap["melos_tiles_appliances_01_19"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_42"} }}
overlayMap["melos_tiles_appliances_01_20"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_32", "appliances_01_34", "appliances_01_37", "appliances_01_38"} }}
overlayMap["melos_tiles_appliances_01_21"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_25", "appliances_01_35", "appliances_01_37", "appliances_01_39"} }}
overlayMap["melos_tiles_appliances_01_22"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_43"} }}
overlayMap["melos_tiles_appliances_01_23"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_42"} }}
overlayMap["melos_tiles_appliances_01_24"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_32", "appliances_01_36", "appliances_01_37", "appliances_01_38"} }}
overlayMap["melos_tiles_appliances_01_25"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_25", "appliances_01_35", "appliances_01_38", "appliances_01_39"} }}
overlayMap["melos_tiles_appliances_01_26"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_43"} }}
overlayMap["melos_tiles_appliances_01_27"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_42"} }}
overlayMap["melos_tiles_appliances_01_28"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_32", "appliances_01_36", "appliances_01_37", "appliances_01_38"} }}
overlayMap["melos_tiles_appliances_01_29"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_25", "appliances_01_35", "appliances_01_37", "appliances_01_39"} }}
overlayMap["melos_tiles_appliances_01_30"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_43"} }}
overlayMap["melos_tiles_appliances_01_31"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_41"} }}
overlayMap["melos_tiles_appliances_01_64"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_2", "appliances_01_4", "appliances_01_16", "appliances_01_22", "storage_01_27"} }}
overlayMap["melos_tiles_appliances_01_65"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_3", "appliances_01_5", "appliances_01_7"} }}
overlayMap["melos_tiles_appliances_01_66"] = {{ name = "other", chance = 1, usage = "", tiles = {"none"} }}
overlayMap["melos_tiles_appliances_01_68"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_16", "appliances_01_22", "appliances_01_2", "appliances_01_4", "storage_01_27"} }}
overlayMap["melos_tiles_appliances_01_69"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_3", "appliances_01_7", "appliances_01_23"} }}
overlayMap["melos_tiles_appliances_01_72"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_2", "appliances_01_4", "appliances_01_6", "appliances_01_16", "appliances_01_22", "storage_01_27"} }}
overlayMap["melos_tiles_appliances_01_73"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_3", "appliances_01_19", "appliances_01_17"} }}
overlayMap["melos_tiles_appliances_01_76"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_2", "appliances_01_4", "appliances_01_6", "appliances_01_16", "appliances_01_22", "storage_01_27"} }}
overlayMap["melos_tiles_appliances_01_77"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_3", "appliances_01_17", "appliances_01_19"} }}
overlayMap["melos_tiles_appliances_01_96"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_2", "appliances_01_4", "appliances_01_6", "appliances_01_22", "appliances_01_20", "storage_01_27"} }}
overlayMap["melos_tiles_appliances_01_97"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_3", "appliances_01_7", "appliances_01_17"} }}
overlayMap["melos_tiles_appliances_01_100"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_2", "appliances_01_4", "appliances_01_6", "appliances_01_16", "appliances_01_20", "appliances_01_22", "storage_01_27"} }}
overlayMap["melos_tiles_appliances_01_101"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_3", "appliances_01_7", "appliances_01_17", "appliances_01_19"} }}
overlayMap["melos_tiles_appliances_01_104"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_2", "appliances_01_4", "appliances_01_6", "appliances_01_16", "appliances_01_18", "appliances_01_20", "appliances_01_22", "storage_01_27"} }}
overlayMap["melos_tiles_appliances_01_105"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_3", "appliances_01_7", "appliances_01_17", "appliances_01_19"} }}
overlayMap["melos_tiles_appliances_01_108"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_2", "appliances_01_4", "appliances_01_6", "appliances_01_16", "appliances_01_18", "appliances_01_20", "appliances_01_22", "storage_01_27"} }}
overlayMap["melos_tiles_appliances_01_109"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_3", "appliances_01_7", "appliances_01_17"} }}
overlayMap["melos_tiles_appliances_02_64"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_48", "appliances_01_50", "fixtures_01_4", "fixtures_01_5", "fixtures_01_8"} }}
overlayMap["melos_tiles_appliances_02_65"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_49", "appliances_01_50", "storage_01_71", "storage_01_62"} }}
overlayMap["melos_tiles_appliances_02_66"] = {{ name = "other", chance = 1, usage = "", tiles = {"storage_01_18", "storage_01_62", "storage_01_70", "storage_01_1", "fixtures_01_4"} }}
overlayMap["melos_tiles_appliances_02_68"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_48", "appliances_01_50", "storage_01_70", "fixtures_01_4", "fixtures_01_5"} }}
overlayMap["melos_tiles_appliances_02_69"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_49", "appliances_01_50", "storage_01_70", "storage_01_62", "storage_01_71", "fixtures_01_4"} }}
overlayMap["melos_tiles_appliances_02_70"] = {{ name = "other", chance = 1, usage = "", tiles = {"storage_01_70", "storage_01_62", "storage_01_1"} }}
overlayMap["melos_tiles_appliances_02_71"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_5", "storage_01_62", "storage_01_70", "storage_01_71", "storage_01_66", "desks_01_34"} }}
overlayMap["melos_tiles_appliances_02_72"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_48", "appliances_01_50", "storage_01_70", "storage_01_71", "desks_01_68"} }}
overlayMap["melos_tiles_appliances_02_73"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_49", "appliances_01_50", "storage_01_71", "storage_01_66"} }}
overlayMap["melos_tiles_appliances_02_74"] = {{ name = "other", chance = 1, usage = "", tiles = {"storage_01_70", "storage_01_71", "storage_01_66", "storage_01_62", "storage_01_1", "desks_01_54"} }}
overlayMap["melos_tiles_appliances_02_76"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_48", "appliances_01_50", "storage_01_70", "storage_01_71", "storage_01_66"} }}
overlayMap["melos_tiles_appliances_02_77"] = {{ name = "other", chance = 1, usage = "", tiles = {"appliances_01_49", "appliances_01_50", "storage_01_70", "storage_01_71", "storage_01_66", "storage_01_62"} }}
overlayMap["melos_tiles_furniture_bathroom_01_4"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_16", "fixtures_01_4", "fixtures_01_8", "fixtures_01_20"} }}
overlayMap["melos_tiles_furniture_bathroom_01_5"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_5", "fixtures_01_9", "fixtures_01_17", "fixtures_01_21"} }}
overlayMap["melos_tiles_furniture_bathroom_01_6"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_6", "fixtures_01_10", "fixtures_01_18", "fixtures_01_22"} }}
overlayMap["melos_tiles_furniture_bathroom_01_7"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_7", "fixtures_01_19", "fixtures_01_23"} }}
overlayMap["melos_tiles_furniture_bathroom_01_16"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_24", "fixtures_01_26", "fixtures_01_27", "fixtures_01_28", "fixtures_01_31", "fixtures_01_32", "fixtures_01_34"} }}
overlayMap["melos_tiles_furniture_bathroom_01_17"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_25", "fixtures_01_27", "fixtures_01_29", "fixtures_01_33", "fixtures_01_35", "fixtures_01_37"} }}
overlayMap["melos_tiles_furniture_bathroom_01_18"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_24", "fixtures_01_26", "fixtures_01_27", "fixtures_01_28", "fixtures_01_32", "fixtures_01_34", "fixtures_01_38"} }}
overlayMap["melos_tiles_furniture_bathroom_01_19"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_24", "fixtures_01_25", "fixtures_01_27", "fixtures_01_31", "fixtures_01_32", "fixtures_01_33", "fixtures_01_35", "fixtures_01_39"} }}
overlayMap["melos_tiles_furniture_bathroom_01_20"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_27", "fixtures_01_35", "fixtures_01_36"} }}
overlayMap["melos_tiles_furniture_bathroom_01_21"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_25", "fixtures_01_29", "fixtures_01_33", "fixtures_01_35", "fixtures_01_37"} }}
overlayMap["melos_tiles_furniture_bathroom_01_22"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_24", "fixtures_01_26", "fixtures_01_28", "fixtures_01_30", "fixtures_01_32", "fixtures_01_34", "fixtures_01_38"} }}
overlayMap["melos_tiles_furniture_bathroom_01_23"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_27", "fixtures_01_31", "fixtures_01_39"} }}
overlayMap["melos_tiles_furniture_bathroom_01_24"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_20"} }}
overlayMap["melos_tiles_furniture_bathroom_01_25"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_10", "fixtures_01_14", "fixtures_01_21"} }}
overlayMap["melos_tiles_furniture_bathroom_01_26"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_19", "fixtures_01_20"} }}
overlayMap["melos_tiles_furniture_bathroom_01_27"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_18", "fixtures_01_22"} }}
overlayMap["melos_tiles_furniture_bathroom_01_28"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_16", "fixtures_01_4", "fixtures_01_20"} }}
overlayMap["melos_tiles_furniture_bathroom_01_29"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_5", "fixtures_01_21"} }}
overlayMap["melos_tiles_furniture_bathroom_01_30"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_18", "fixtures_01_21", "fixtures_01_7"} }}
overlayMap["melos_tiles_furniture_bathroom_01_31"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_6", "fixtures_01_19"} }}
overlayMap["melos_tiles_furniture_bathroom_01_32"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_23"} }}
overlayMap["melos_tiles_furniture_bathroom_01_33"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_22"} }}
overlayMap["melos_tiles_furniture_bathroom_01_34"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_23"} }}
overlayMap["melos_tiles_furniture_bathroom_01_35"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_22"} }}
overlayMap["melos_tiles_furniture_bathroom_01_36"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_23"} }}
overlayMap["melos_tiles_furniture_bathroom_01_37"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_22"} }}
overlayMap["melos_tiles_furniture_bathroom_01_38"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_22"} }}
overlayMap["melos_tiles_furniture_bathroom_01_39"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_23"} }}
overlayMap["melos_tiles_furniture_bathroom_01_44"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_4", "fixtures_01_20"} }}
overlayMap["melos_tiles_furniture_bathroom_01_45"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_21", "fixtures_01_5"} }}
overlayMap["melos_tiles_furniture_bathroom_01_46"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_7", "fixtures_01_22", "fixtures_01_18"} }}
overlayMap["melos_tiles_furniture_bathroom_01_47"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_6", "fixtures_01_23"} }}
overlayMap["melos_tiles_furniture_bathroom_01_56"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_24", "fixtures_01_27", "fixtures_01_28", "fixtures_01_31", "fixtures_01_32", "fixtures_01_36", "fixtures_01_35"} }}
overlayMap["melos_tiles_furniture_bathroom_01_57"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_25", "fixtures_01_29", "fixtures_01_33", "fixtures_01_34", "fixtures_01_35", "fixtures_01_37"} }}
overlayMap["melos_tiles_furniture_bathroom_01_58"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_24", "fixtures_01_26", "fixtures_01_28", "fixtures_01_30", "fixtures_01_32", "fixtures_01_33", "fixtures_01_34", "fixtures_01_38"} }}
overlayMap["melos_tiles_furniture_bathroom_01_59"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_24", "fixtures_01_25", "fixtures_01_27", "fixtures_01_28", "fixtures_01_31", "fixtures_01_32", "fixtures_01_33", "fixtures_01_35", "fixtures_01_36"} }}
overlayMap["melos_tiles_furniture_bathroom_01_60"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_36", "fixtures_01_35", "fixtures_01_32", "fixtures_01_27"} }}
overlayMap["melos_tiles_furniture_bathroom_01_61"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_25", "fixtures_01_29", "fixtures_01_33", "fixtures_01_35", "fixtures_01_37"} }}
overlayMap["melos_tiles_furniture_bathroom_01_62"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_24", "fixtures_01_26", "fixtures_01_28", "fixtures_01_30", "fixtures_01_32", "fixtures_01_33", "fixtures_01_34", "fixtures_01_38"} }}
overlayMap["melos_tiles_furniture_bathroom_01_63"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_39", "fixtures_01_35", "fixtures_01_32", "fixtures_01_28", "fixtures_01_27", "fixtures_01_24"} }}
overlayMap["melos_tiles_furniture_bathroom_01_64"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_23"} }}
overlayMap["melos_tiles_furniture_bathroom_01_65"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_22", "fixtures_01_21", "fixtures_01_5"} }}
overlayMap["melos_tiles_furniture_bathroom_01_66"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_6"} }}
overlayMap["melos_tiles_furniture_bathroom_01_67"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_7", "fixtures_01_22"} }}
overlayMap["melos_tiles_furniture_bathroom_01_68"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_20", "fixtures_01_23"} }}
overlayMap["melos_tiles_furniture_bathroom_01_69"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_21"} }}
overlayMap["melos_tiles_furniture_bathroom_01_70"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_18", "fixtures_01_21", "fixtures_01_22"} }}
overlayMap["melos_tiles_furniture_bathroom_01_71"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_23", "fixtures_01_20", "fixtures_01_19"} }}
overlayMap["melos_tiles_furniture_bathroom_01_72"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_23"} }}
overlayMap["melos_tiles_furniture_bathroom_01_73"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_22"} }}
overlayMap["melos_tiles_furniture_bathroom_01_76"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_23"} }}
overlayMap["melos_tiles_furniture_bathroom_01_77"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_22"} }}
overlayMap["melos_tiles_furniture_bathroom_01_78"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_22"} }}
overlayMap["melos_tiles_furniture_bathroom_01_84"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_16", "fixtures_01_4", "fixtures_01_8", "fixtures_01_20"} }}
overlayMap["melos_tiles_furniture_bathroom_01_85"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_5", "fixtures_01_9", "fixtures_01_17", "fixtures_01_21"} }}
overlayMap["melos_tiles_furniture_bathroom_01_86"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_6", "fixtures_01_10", "fixtures_01_18", "fixtures_01_22"} }}
overlayMap["melos_tiles_furniture_bathroom_01_87"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_7", "fixtures_01_19", "fixtures_01_23"} }}
overlayMap["melos_tiles_furniture_bathroom_01_96"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_24", "fixtures_01_26", "fixtures_01_27", "fixtures_01_28", "fixtures_01_31", "fixtures_01_32", "fixtures_01_34"} }}
overlayMap["melos_tiles_furniture_bathroom_01_97"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_25", "fixtures_01_27", "fixtures_01_29", "fixtures_01_33", "fixtures_01_35", "fixtures_01_37"} }}
overlayMap["melos_tiles_furniture_bathroom_01_98"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_24", "fixtures_01_26", "fixtures_01_27", "fixtures_01_28", "fixtures_01_32", "fixtures_01_34", "fixtures_01_38"} }}
overlayMap["melos_tiles_furniture_bathroom_01_99"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_24", "fixtures_01_25", "fixtures_01_27", "fixtures_01_31", "fixtures_01_32", "fixtures_01_33", "fixtures_01_35", "fixtures_01_39"} }}
overlayMap["melos_tiles_furniture_bathroom_01_100"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_27", "fixtures_01_35", "fixtures_01_36"} }}
overlayMap["melos_tiles_furniture_bathroom_01_101"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_25", "fixtures_01_29", "fixtures_01_33", "fixtures_01_35", "fixtures_01_37"} }}
overlayMap["melos_tiles_furniture_bathroom_01_102"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_24", "fixtures_01_26", "fixtures_01_28", "fixtures_01_30", "fixtures_01_32", "fixtures_01_34", "fixtures_01_38"} }}
overlayMap["melos_tiles_furniture_bathroom_01_103"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_27", "fixtures_01_31", "fixtures_01_39"} }}
overlayMap["melos_tiles_furniture_bathroom_01_104"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_20"} }}
overlayMap["melos_tiles_furniture_bathroom_01_105"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_10", "fixtures_01_14", "fixtures_01_21"} }}
overlayMap["melos_tiles_furniture_bathroom_01_106"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_19", "fixtures_01_20"} }}
overlayMap["melos_tiles_furniture_bathroom_01_107"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_18", "fixtures_01_22"} }}
overlayMap["melos_tiles_furniture_bathroom_01_108"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_16", "fixtures_01_4", "fixtures_01_20"} }}
overlayMap["melos_tiles_furniture_bathroom_01_109"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_5", "fixtures_01_21"} }}
overlayMap["melos_tiles_furniture_bathroom_01_110"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_18", "fixtures_01_21", "fixtures_01_7"} }}
overlayMap["melos_tiles_furniture_bathroom_01_111"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_6", "fixtures_01_19"} }}
overlayMap["melos_tiles_furniture_bathroom_01_112"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_23"} }}
overlayMap["melos_tiles_furniture_bathroom_01_113"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_22"} }}
overlayMap["melos_tiles_furniture_bathroom_01_114"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_23"} }}
overlayMap["melos_tiles_furniture_bathroom_01_115"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_22"} }}
overlayMap["melos_tiles_furniture_bathroom_01_116"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_23"} }}
overlayMap["melos_tiles_furniture_bathroom_01_117"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_22"} }}
overlayMap["melos_tiles_furniture_bathroom_01_118"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_22"} }}
overlayMap["melos_tiles_furniture_bathroom_01_119"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_23"} }}
overlayMap["melos_tiles_furniture_bathroom_02_4"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_16", "fixtures_01_4", "fixtures_01_8", "fixtures_01_20"} }}
overlayMap["melos_tiles_furniture_bathroom_02_5"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_5", "fixtures_01_9", "fixtures_01_17", "fixtures_01_21"} }}
overlayMap["melos_tiles_furniture_bathroom_02_6"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_6", "fixtures_01_10", "fixtures_01_18", "fixtures_01_22"} }}
overlayMap["melos_tiles_furniture_bathroom_02_7"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_7", "fixtures_01_19", "fixtures_01_23"} }}
overlayMap["melos_tiles_furniture_bathroom_02_16"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_24", "fixtures_01_26", "fixtures_01_27", "fixtures_01_28", "fixtures_01_31", "fixtures_01_32", "fixtures_01_34"} }}
overlayMap["melos_tiles_furniture_bathroom_02_17"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_25", "fixtures_01_27", "fixtures_01_29", "fixtures_01_33", "fixtures_01_35", "fixtures_01_37"} }}
overlayMap["melos_tiles_furniture_bathroom_02_18"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_24", "fixtures_01_26", "fixtures_01_27", "fixtures_01_28", "fixtures_01_32", "fixtures_01_34", "fixtures_01_38"} }}
overlayMap["melos_tiles_furniture_bathroom_02_19"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_24", "fixtures_01_25", "fixtures_01_27", "fixtures_01_31", "fixtures_01_32", "fixtures_01_33", "fixtures_01_35", "fixtures_01_39"} }}
overlayMap["melos_tiles_furniture_bathroom_02_20"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_27", "fixtures_01_35", "fixtures_01_36"} }}
overlayMap["melos_tiles_furniture_bathroom_02_21"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_25", "fixtures_01_29", "fixtures_01_33", "fixtures_01_35", "fixtures_01_37"} }}
overlayMap["melos_tiles_furniture_bathroom_02_22"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_24", "fixtures_01_26", "fixtures_01_28", "fixtures_01_30", "fixtures_01_32", "fixtures_01_34", "fixtures_01_38"} }}
overlayMap["melos_tiles_furniture_bathroom_02_23"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_27", "fixtures_01_31", "fixtures_01_39"} }}
overlayMap["melos_tiles_furniture_bathroom_02_24"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_20"} }}
overlayMap["melos_tiles_furniture_bathroom_02_25"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_10", "fixtures_01_14", "fixtures_01_21"} }}
overlayMap["melos_tiles_furniture_bathroom_02_26"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_19", "fixtures_01_20"} }}
overlayMap["melos_tiles_furniture_bathroom_02_27"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_18", "fixtures_01_22"} }}
overlayMap["melos_tiles_furniture_bathroom_02_28"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_16", "fixtures_01_4", "fixtures_01_20"} }}
overlayMap["melos_tiles_furniture_bathroom_02_29"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_5", "fixtures_01_21"} }}
overlayMap["melos_tiles_furniture_bathroom_02_30"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_18", "fixtures_01_21", "fixtures_01_7"} }}
overlayMap["melos_tiles_furniture_bathroom_02_31"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_6", "fixtures_01_19"} }}
overlayMap["melos_tiles_furniture_bathroom_02_32"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_23"} }}
overlayMap["melos_tiles_furniture_bathroom_02_33"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_22"} }}
overlayMap["melos_tiles_furniture_bathroom_02_34"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_23"} }}
overlayMap["melos_tiles_furniture_bathroom_02_35"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_22"} }}
overlayMap["melos_tiles_furniture_bathroom_02_36"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_23"} }}
overlayMap["melos_tiles_furniture_bathroom_02_37"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_22"} }}
overlayMap["melos_tiles_furniture_bathroom_02_38"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_22"} }}
overlayMap["melos_tiles_furniture_bathroom_02_39"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_23"} }}
overlayMap["melos_tiles_furniture_bathroom_02_44"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_4", "fixtures_01_20"} }}
overlayMap["melos_tiles_furniture_bathroom_02_45"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_21", "fixtures_01_5"} }}
overlayMap["melos_tiles_furniture_bathroom_02_46"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_7", "fixtures_01_22", "fixtures_01_18"} }}
overlayMap["melos_tiles_furniture_bathroom_02_47"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_6", "fixtures_01_23"} }}
overlayMap["melos_tiles_furniture_bathroom_02_56"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_24", "fixtures_01_27", "fixtures_01_28", "fixtures_01_31", "fixtures_01_32", "fixtures_01_36", "fixtures_01_35"} }}
overlayMap["melos_tiles_furniture_bathroom_02_57"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_25", "fixtures_01_29", "fixtures_01_33", "fixtures_01_34", "fixtures_01_35", "fixtures_01_37"} }}
overlayMap["melos_tiles_furniture_bathroom_02_58"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_24", "fixtures_01_26", "fixtures_01_28", "fixtures_01_30", "fixtures_01_32", "fixtures_01_33", "fixtures_01_34", "fixtures_01_38"} }}
overlayMap["melos_tiles_furniture_bathroom_02_59"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_24", "fixtures_01_25", "fixtures_01_27", "fixtures_01_28", "fixtures_01_31", "fixtures_01_32", "fixtures_01_33", "fixtures_01_35", "fixtures_01_36"} }}
overlayMap["melos_tiles_furniture_bathroom_02_60"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_36", "fixtures_01_35", "fixtures_01_32", "fixtures_01_27"} }}
overlayMap["melos_tiles_furniture_bathroom_02_61"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_25", "fixtures_01_29", "fixtures_01_33", "fixtures_01_35", "fixtures_01_37"} }}
overlayMap["melos_tiles_furniture_bathroom_02_62"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_24", "fixtures_01_26", "fixtures_01_28", "fixtures_01_30", "fixtures_01_32", "fixtures_01_33", "fixtures_01_34", "fixtures_01_38"} }}
overlayMap["melos_tiles_furniture_bathroom_02_63"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_39", "fixtures_01_35", "fixtures_01_32", "fixtures_01_28", "fixtures_01_27", "fixtures_01_24"} }}
overlayMap["melos_tiles_furniture_bathroom_02_64"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_23"} }}
overlayMap["melos_tiles_furniture_bathroom_02_65"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_22", "fixtures_01_21", "fixtures_01_5"} }}
overlayMap["melos_tiles_furniture_bathroom_02_66"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_6"} }}
overlayMap["melos_tiles_furniture_bathroom_02_67"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_7", "fixtures_01_22"} }}
overlayMap["melos_tiles_furniture_bathroom_02_68"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_20", "fixtures_01_23"} }}
overlayMap["melos_tiles_furniture_bathroom_02_69"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_21"} }}
overlayMap["melos_tiles_furniture_bathroom_02_70"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_18", "fixtures_01_21", "fixtures_01_22"} }}
overlayMap["melos_tiles_furniture_bathroom_02_71"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_23", "fixtures_01_20", "fixtures_01_19"} }}
overlayMap["melos_tiles_furniture_bathroom_02_72"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_23"} }}
overlayMap["melos_tiles_furniture_bathroom_02_73"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_22"} }}
overlayMap["melos_tiles_furniture_bathroom_02_76"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_23"} }}
overlayMap["melos_tiles_furniture_bathroom_02_77"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_22"} }}
overlayMap["melos_tiles_furniture_bathroom_02_78"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_22"} }}
overlayMap["melos_tiles_furniture_bathroom_02_84"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_16", "fixtures_01_4", "fixtures_01_8", "fixtures_01_20"} }}
overlayMap["melos_tiles_furniture_bathroom_02_85"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_5", "fixtures_01_9", "fixtures_01_17", "fixtures_01_21"} }}
overlayMap["melos_tiles_furniture_bathroom_02_86"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_6", "fixtures_01_10", "fixtures_01_18", "fixtures_01_22"} }}
overlayMap["melos_tiles_furniture_bathroom_02_87"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_7", "fixtures_01_19", "fixtures_01_23"} }}
overlayMap["melos_tiles_furniture_bathroom_02_96"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_24", "fixtures_01_26", "fixtures_01_27", "fixtures_01_28", "fixtures_01_31", "fixtures_01_32", "fixtures_01_34"} }}
overlayMap["melos_tiles_furniture_bathroom_02_97"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_25", "fixtures_01_27", "fixtures_01_29", "fixtures_01_33", "fixtures_01_35", "fixtures_01_37"} }}
overlayMap["melos_tiles_furniture_bathroom_02_98"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_24", "fixtures_01_26", "fixtures_01_27", "fixtures_01_28", "fixtures_01_32", "fixtures_01_34", "fixtures_01_38"} }}
overlayMap["melos_tiles_furniture_bathroom_02_99"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_24", "fixtures_01_25", "fixtures_01_27", "fixtures_01_31", "fixtures_01_32", "fixtures_01_33", "fixtures_01_35", "fixtures_01_39"} }}
overlayMap["melos_tiles_furniture_bathroom_02_100"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_27", "fixtures_01_35", "fixtures_01_36"} }}
overlayMap["melos_tiles_furniture_bathroom_02_101"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_25", "fixtures_01_29", "fixtures_01_33", "fixtures_01_35", "fixtures_01_37"} }}
overlayMap["melos_tiles_furniture_bathroom_02_102"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_24", "fixtures_01_26", "fixtures_01_28", "fixtures_01_30", "fixtures_01_32", "fixtures_01_34", "fixtures_01_38"} }}
overlayMap["melos_tiles_furniture_bathroom_02_103"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_27", "fixtures_01_31", "fixtures_01_39"} }}
overlayMap["melos_tiles_furniture_bathroom_02_104"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_20"} }}
overlayMap["melos_tiles_furniture_bathroom_02_105"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_10", "fixtures_01_14", "fixtures_01_21"} }}
overlayMap["melos_tiles_furniture_bathroom_02_106"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_19", "fixtures_01_20"} }}
overlayMap["melos_tiles_furniture_bathroom_02_107"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_18", "fixtures_01_22"} }}
overlayMap["melos_tiles_furniture_bathroom_02_108"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_16", "fixtures_01_4", "fixtures_01_20"} }}
overlayMap["melos_tiles_furniture_bathroom_02_109"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_5", "fixtures_01_21"} }}
overlayMap["melos_tiles_furniture_bathroom_02_110"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_18", "fixtures_01_21", "fixtures_01_7"} }}
overlayMap["melos_tiles_furniture_bathroom_02_111"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_6", "fixtures_01_19"} }}
overlayMap["melos_tiles_furniture_bathroom_02_112"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_23"} }}
overlayMap["melos_tiles_furniture_bathroom_02_113"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_22"} }}
overlayMap["melos_tiles_furniture_bathroom_02_114"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_23"} }}
overlayMap["melos_tiles_furniture_bathroom_02_115"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_22"} }}
overlayMap["melos_tiles_furniture_bathroom_02_116"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_23"} }}
overlayMap["melos_tiles_furniture_bathroom_02_117"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_22"} }}
overlayMap["melos_tiles_furniture_bathroom_02_118"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_22"} }}
overlayMap["melos_tiles_furniture_bathroom_02_119"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_23"} }}
overlayMap["melos_tiles_furniture_bathroom_03_4"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_16", "fixtures_01_4", "fixtures_01_8", "fixtures_01_20"} }}
overlayMap["melos_tiles_furniture_bathroom_03_5"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_5", "fixtures_01_9", "fixtures_01_17", "fixtures_01_21"} }}
overlayMap["melos_tiles_furniture_bathroom_03_6"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_6", "fixtures_01_10", "fixtures_01_18", "fixtures_01_22"} }}
overlayMap["melos_tiles_furniture_bathroom_03_7"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_7", "fixtures_01_19", "fixtures_01_23"} }}
overlayMap["melos_tiles_furniture_bathroom_03_16"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_24", "fixtures_01_26", "fixtures_01_27", "fixtures_01_28", "fixtures_01_31", "fixtures_01_32", "fixtures_01_34"} }}
overlayMap["melos_tiles_furniture_bathroom_03_17"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_25", "fixtures_01_27", "fixtures_01_29", "fixtures_01_33", "fixtures_01_35", "fixtures_01_37"} }}
overlayMap["melos_tiles_furniture_bathroom_03_18"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_24", "fixtures_01_26", "fixtures_01_27", "fixtures_01_28", "fixtures_01_32", "fixtures_01_34", "fixtures_01_38"} }}
overlayMap["melos_tiles_furniture_bathroom_03_19"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_24", "fixtures_01_25", "fixtures_01_27", "fixtures_01_31", "fixtures_01_32", "fixtures_01_33", "fixtures_01_35", "fixtures_01_39"} }}
overlayMap["melos_tiles_furniture_bathroom_03_20"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_27", "fixtures_01_35", "fixtures_01_36"} }}
overlayMap["melos_tiles_furniture_bathroom_03_21"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_25", "fixtures_01_29", "fixtures_01_33", "fixtures_01_35", "fixtures_01_37"} }}
overlayMap["melos_tiles_furniture_bathroom_03_22"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_24", "fixtures_01_26", "fixtures_01_28", "fixtures_01_30", "fixtures_01_32", "fixtures_01_34", "fixtures_01_38"} }}
overlayMap["melos_tiles_furniture_bathroom_03_23"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_27", "fixtures_01_31", "fixtures_01_39"} }}
overlayMap["melos_tiles_furniture_bathroom_03_24"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_20"} }}
overlayMap["melos_tiles_furniture_bathroom_03_25"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_10", "fixtures_01_14", "fixtures_01_21"} }}
overlayMap["melos_tiles_furniture_bathroom_03_26"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_19", "fixtures_01_20"} }}
overlayMap["melos_tiles_furniture_bathroom_03_27"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_18", "fixtures_01_22"} }}
overlayMap["melos_tiles_furniture_bathroom_03_28"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_16", "fixtures_01_4", "fixtures_01_20"} }}
overlayMap["melos_tiles_furniture_bathroom_03_29"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_5", "fixtures_01_21"} }}
overlayMap["melos_tiles_furniture_bathroom_03_30"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_18", "fixtures_01_21", "fixtures_01_7"} }}
overlayMap["melos_tiles_furniture_bathroom_03_31"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_6", "fixtures_01_19"} }}
overlayMap["melos_tiles_furniture_bathroom_03_32"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_23"} }}
overlayMap["melos_tiles_furniture_bathroom_03_33"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_22"} }}
overlayMap["melos_tiles_furniture_bathroom_03_34"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_23"} }}
overlayMap["melos_tiles_furniture_bathroom_03_35"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_22"} }}
overlayMap["melos_tiles_furniture_bathroom_03_36"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_23"} }}
overlayMap["melos_tiles_furniture_bathroom_03_37"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_22"} }}
overlayMap["melos_tiles_furniture_bathroom_03_38"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_22"} }}
overlayMap["melos_tiles_furniture_bathroom_03_39"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_23"} }}
overlayMap["melos_tiles_furniture_bathroom_03_44"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_4", "fixtures_01_20"} }}
overlayMap["melos_tiles_furniture_bathroom_03_45"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_21", "fixtures_01_5"} }}
overlayMap["melos_tiles_furniture_bathroom_03_46"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_7", "fixtures_01_22", "fixtures_01_18"} }}
overlayMap["melos_tiles_furniture_bathroom_03_47"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_6", "fixtures_01_23"} }}
overlayMap["melos_tiles_furniture_bathroom_03_56"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_24", "fixtures_01_27", "fixtures_01_28", "fixtures_01_31", "fixtures_01_32", "fixtures_01_36", "fixtures_01_35"} }}
overlayMap["melos_tiles_furniture_bathroom_03_57"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_25", "fixtures_01_29", "fixtures_01_33", "fixtures_01_34", "fixtures_01_35", "fixtures_01_37"} }}
overlayMap["melos_tiles_furniture_bathroom_03_58"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_24", "fixtures_01_26", "fixtures_01_28", "fixtures_01_30", "fixtures_01_32", "fixtures_01_33", "fixtures_01_34", "fixtures_01_38"} }}
overlayMap["melos_tiles_furniture_bathroom_03_59"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_24", "fixtures_01_25", "fixtures_01_27", "fixtures_01_28", "fixtures_01_31", "fixtures_01_32", "fixtures_01_33", "fixtures_01_35", "fixtures_01_36"} }}
overlayMap["melos_tiles_furniture_bathroom_03_60"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_36", "fixtures_01_35", "fixtures_01_32", "fixtures_01_27"} }}
overlayMap["melos_tiles_furniture_bathroom_03_61"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_25", "fixtures_01_29", "fixtures_01_33", "fixtures_01_35", "fixtures_01_37"} }}
overlayMap["melos_tiles_furniture_bathroom_03_62"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_24", "fixtures_01_26", "fixtures_01_28", "fixtures_01_30", "fixtures_01_32", "fixtures_01_33", "fixtures_01_34", "fixtures_01_38"} }}
overlayMap["melos_tiles_furniture_bathroom_03_63"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_39", "fixtures_01_35", "fixtures_01_32", "fixtures_01_28", "fixtures_01_27", "fixtures_01_24"} }}
overlayMap["melos_tiles_furniture_bathroom_03_64"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_23"} }}
overlayMap["melos_tiles_furniture_bathroom_03_65"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_22", "fixtures_01_21", "fixtures_01_5"} }}
overlayMap["melos_tiles_furniture_bathroom_03_66"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_6"} }}
overlayMap["melos_tiles_furniture_bathroom_03_67"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_7", "fixtures_01_22"} }}
overlayMap["melos_tiles_furniture_bathroom_03_68"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_20", "fixtures_01_23"} }}
overlayMap["melos_tiles_furniture_bathroom_03_69"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_21"} }}
overlayMap["melos_tiles_furniture_bathroom_03_70"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_18", "fixtures_01_21", "fixtures_01_22"} }}
overlayMap["melos_tiles_furniture_bathroom_03_71"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_23", "fixtures_01_20", "fixtures_01_19"} }}
overlayMap["melos_tiles_furniture_bathroom_03_72"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_23"} }}
overlayMap["melos_tiles_furniture_bathroom_03_73"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_22"} }}
overlayMap["melos_tiles_furniture_bathroom_03_76"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_23"} }}
overlayMap["melos_tiles_furniture_bathroom_03_77"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_22"} }}
overlayMap["melos_tiles_furniture_bathroom_03_78"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_22"} }}
overlayMap["melos_tiles_furniture_bathroom_03_84"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_16", "fixtures_01_4", "fixtures_01_8", "fixtures_01_20"} }}
overlayMap["melos_tiles_furniture_bathroom_03_85"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_5", "fixtures_01_9", "fixtures_01_17", "fixtures_01_21"} }}
overlayMap["melos_tiles_furniture_bathroom_03_86"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_6", "fixtures_01_10", "fixtures_01_18", "fixtures_01_22"} }}
overlayMap["melos_tiles_furniture_bathroom_03_87"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_7", "fixtures_01_19", "fixtures_01_23"} }}
overlayMap["melos_tiles_furniture_bathroom_03_96"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_24", "fixtures_01_26", "fixtures_01_27", "fixtures_01_28", "fixtures_01_31", "fixtures_01_32", "fixtures_01_34"} }}
overlayMap["melos_tiles_furniture_bathroom_03_97"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_25", "fixtures_01_27", "fixtures_01_29", "fixtures_01_33", "fixtures_01_35", "fixtures_01_37"} }}
overlayMap["melos_tiles_furniture_bathroom_03_98"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_24", "fixtures_01_26", "fixtures_01_27", "fixtures_01_28", "fixtures_01_32", "fixtures_01_34", "fixtures_01_38"} }}
overlayMap["melos_tiles_furniture_bathroom_03_99"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_24", "fixtures_01_25", "fixtures_01_27", "fixtures_01_31", "fixtures_01_32", "fixtures_01_33", "fixtures_01_35", "fixtures_01_39"} }}
overlayMap["melos_tiles_furniture_bathroom_03_100"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_27", "fixtures_01_35", "fixtures_01_36"} }}
overlayMap["melos_tiles_furniture_bathroom_03_101"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_25", "fixtures_01_29", "fixtures_01_33", "fixtures_01_35", "fixtures_01_37"} }}
overlayMap["melos_tiles_furniture_bathroom_03_102"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_24", "fixtures_01_26", "fixtures_01_28", "fixtures_01_30", "fixtures_01_32", "fixtures_01_34", "fixtures_01_38"} }}
overlayMap["melos_tiles_furniture_bathroom_03_103"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_27", "fixtures_01_31", "fixtures_01_39"} }}
overlayMap["melos_tiles_furniture_bathroom_03_104"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_20"} }}
overlayMap["melos_tiles_furniture_bathroom_03_105"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_10", "fixtures_01_14", "fixtures_01_21"} }}
overlayMap["melos_tiles_furniture_bathroom_03_106"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_19", "fixtures_01_20"} }}
overlayMap["melos_tiles_furniture_bathroom_03_107"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_18", "fixtures_01_22"} }}
overlayMap["melos_tiles_furniture_bathroom_03_108"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_16", "fixtures_01_4", "fixtures_01_20"} }}
overlayMap["melos_tiles_furniture_bathroom_03_109"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_5", "fixtures_01_21"} }}
overlayMap["melos_tiles_furniture_bathroom_03_110"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_18", "fixtures_01_21", "fixtures_01_7"} }}
overlayMap["melos_tiles_furniture_bathroom_03_111"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_6", "fixtures_01_19"} }}
overlayMap["melos_tiles_furniture_bathroom_03_112"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_23"} }}
overlayMap["melos_tiles_furniture_bathroom_03_113"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_22"} }}
overlayMap["melos_tiles_furniture_bathroom_03_114"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_23"} }}
overlayMap["melos_tiles_furniture_bathroom_03_115"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_22"} }}
overlayMap["melos_tiles_furniture_bathroom_03_116"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_23"} }}
overlayMap["melos_tiles_furniture_bathroom_03_117"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_22"} }}
overlayMap["melos_tiles_furniture_bathroom_03_118"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_22"} }}
overlayMap["melos_tiles_furniture_bathroom_03_119"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_23"} }}
overlayMap["melos_tiles_furniture_bathroom_04_4"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_16", "fixtures_01_4", "fixtures_01_8", "fixtures_01_20"} }}
overlayMap["melos_tiles_furniture_bathroom_04_5"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_5", "fixtures_01_9", "fixtures_01_17", "fixtures_01_21"} }}
overlayMap["melos_tiles_furniture_bathroom_04_6"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_6", "fixtures_01_10", "fixtures_01_18", "fixtures_01_22"} }}
overlayMap["melos_tiles_furniture_bathroom_04_7"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_7", "fixtures_01_19", "fixtures_01_23"} }}
overlayMap["melos_tiles_furniture_bathroom_04_16"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_24", "fixtures_01_26", "fixtures_01_27", "fixtures_01_28", "fixtures_01_31", "fixtures_01_32", "fixtures_01_34"} }}
overlayMap["melos_tiles_furniture_bathroom_04_17"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_25", "fixtures_01_27", "fixtures_01_29", "fixtures_01_33", "fixtures_01_35", "fixtures_01_37"} }}
overlayMap["melos_tiles_furniture_bathroom_04_18"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_24", "fixtures_01_26", "fixtures_01_27", "fixtures_01_28", "fixtures_01_32", "fixtures_01_34", "fixtures_01_38"} }}
overlayMap["melos_tiles_furniture_bathroom_04_19"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_24", "fixtures_01_25", "fixtures_01_27", "fixtures_01_31", "fixtures_01_32", "fixtures_01_33", "fixtures_01_35", "fixtures_01_39"} }}
overlayMap["melos_tiles_furniture_bathroom_04_20"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_27", "fixtures_01_35", "fixtures_01_36"} }}
overlayMap["melos_tiles_furniture_bathroom_04_21"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_25", "fixtures_01_29", "fixtures_01_33", "fixtures_01_35", "fixtures_01_37"} }}
overlayMap["melos_tiles_furniture_bathroom_04_22"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_24", "fixtures_01_26", "fixtures_01_28", "fixtures_01_30", "fixtures_01_32", "fixtures_01_34", "fixtures_01_38"} }}
overlayMap["melos_tiles_furniture_bathroom_04_23"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_27", "fixtures_01_31", "fixtures_01_39"} }}
overlayMap["melos_tiles_furniture_bathroom_04_24"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_20"} }}
overlayMap["melos_tiles_furniture_bathroom_04_25"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_10", "fixtures_01_14", "fixtures_01_21"} }}
overlayMap["melos_tiles_furniture_bathroom_04_26"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_19", "fixtures_01_20"} }}
overlayMap["melos_tiles_furniture_bathroom_04_27"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_18", "fixtures_01_22"} }}
overlayMap["melos_tiles_furniture_bathroom_04_28"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_16", "fixtures_01_4", "fixtures_01_20"} }}
overlayMap["melos_tiles_furniture_bathroom_04_29"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_5", "fixtures_01_21"} }}
overlayMap["melos_tiles_furniture_bathroom_04_30"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_18", "fixtures_01_21", "fixtures_01_7"} }}
overlayMap["melos_tiles_furniture_bathroom_04_31"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_6", "fixtures_01_19"} }}
overlayMap["melos_tiles_furniture_bathroom_04_32"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_23"} }}
overlayMap["melos_tiles_furniture_bathroom_04_33"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_22"} }}
overlayMap["melos_tiles_furniture_bathroom_04_34"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_23"} }}
overlayMap["melos_tiles_furniture_bathroom_04_35"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_22"} }}
overlayMap["melos_tiles_furniture_bathroom_04_36"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_23"} }}
overlayMap["melos_tiles_furniture_bathroom_04_37"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_22"} }}
overlayMap["melos_tiles_furniture_bathroom_04_38"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_22"} }}
overlayMap["melos_tiles_furniture_bathroom_04_39"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_23"} }}
overlayMap["melos_tiles_furniture_bathroom_04_44"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_4", "fixtures_01_20"} }}
overlayMap["melos_tiles_furniture_bathroom_04_45"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_21", "fixtures_01_5"} }}
overlayMap["melos_tiles_furniture_bathroom_04_46"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_7", "fixtures_01_22", "fixtures_01_18"} }}
overlayMap["melos_tiles_furniture_bathroom_04_47"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_6", "fixtures_01_23"} }}
overlayMap["melos_tiles_furniture_bathroom_04_56"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_24", "fixtures_01_27", "fixtures_01_28", "fixtures_01_31", "fixtures_01_32", "fixtures_01_36", "fixtures_01_35"} }}
overlayMap["melos_tiles_furniture_bathroom_04_57"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_25", "fixtures_01_29", "fixtures_01_33", "fixtures_01_34", "fixtures_01_35", "fixtures_01_37"} }}
overlayMap["melos_tiles_furniture_bathroom_04_58"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_24", "fixtures_01_26", "fixtures_01_28", "fixtures_01_30", "fixtures_01_32", "fixtures_01_33", "fixtures_01_34", "fixtures_01_38"} }}
overlayMap["melos_tiles_furniture_bathroom_04_59"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_24", "fixtures_01_25", "fixtures_01_27", "fixtures_01_28", "fixtures_01_31", "fixtures_01_32", "fixtures_01_33", "fixtures_01_35", "fixtures_01_36"} }}
overlayMap["melos_tiles_furniture_bathroom_04_60"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_36", "fixtures_01_35", "fixtures_01_32", "fixtures_01_27"} }}
overlayMap["melos_tiles_furniture_bathroom_04_61"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_25", "fixtures_01_29", "fixtures_01_33", "fixtures_01_35", "fixtures_01_37"} }}
overlayMap["melos_tiles_furniture_bathroom_04_62"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_24", "fixtures_01_26", "fixtures_01_28", "fixtures_01_30", "fixtures_01_32", "fixtures_01_33", "fixtures_01_34", "fixtures_01_38"} }}
overlayMap["melos_tiles_furniture_bathroom_04_63"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_39", "fixtures_01_35", "fixtures_01_32", "fixtures_01_28", "fixtures_01_27", "fixtures_01_24"} }}
overlayMap["melos_tiles_furniture_bathroom_04_64"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_23"} }}
overlayMap["melos_tiles_furniture_bathroom_04_65"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_22", "fixtures_01_21", "fixtures_01_5"} }}
overlayMap["melos_tiles_furniture_bathroom_04_66"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_6"} }}
overlayMap["melos_tiles_furniture_bathroom_04_67"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_7", "fixtures_01_22"} }}
overlayMap["melos_tiles_furniture_bathroom_04_68"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_20", "fixtures_01_23"} }}
overlayMap["melos_tiles_furniture_bathroom_04_69"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_21"} }}
overlayMap["melos_tiles_furniture_bathroom_04_70"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_18", "fixtures_01_21", "fixtures_01_22"} }}
overlayMap["melos_tiles_furniture_bathroom_04_71"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_23", "fixtures_01_20", "fixtures_01_19"} }}
overlayMap["melos_tiles_furniture_bathroom_04_72"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_23"} }}
overlayMap["melos_tiles_furniture_bathroom_04_73"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_22"} }}
overlayMap["melos_tiles_furniture_bathroom_04_76"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_23"} }}
overlayMap["melos_tiles_furniture_bathroom_04_77"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_22"} }}
overlayMap["melos_tiles_furniture_bathroom_04_78"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_22"} }}
overlayMap["melos_tiles_furniture_bathroom_04_84"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_16", "fixtures_01_4", "fixtures_01_8", "fixtures_01_20"} }}
overlayMap["melos_tiles_furniture_bathroom_04_85"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_5", "fixtures_01_9", "fixtures_01_17", "fixtures_01_21"} }}
overlayMap["melos_tiles_furniture_bathroom_04_86"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_6", "fixtures_01_10", "fixtures_01_18", "fixtures_01_22"} }}
overlayMap["melos_tiles_furniture_bathroom_04_87"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_7", "fixtures_01_19", "fixtures_01_23"} }}
overlayMap["melos_tiles_furniture_bathroom_04_96"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_24", "fixtures_01_26", "fixtures_01_27", "fixtures_01_28", "fixtures_01_31", "fixtures_01_32", "fixtures_01_34"} }}
overlayMap["melos_tiles_furniture_bathroom_04_97"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_25", "fixtures_01_27", "fixtures_01_29", "fixtures_01_33", "fixtures_01_35", "fixtures_01_37"} }}
overlayMap["melos_tiles_furniture_bathroom_04_98"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_24", "fixtures_01_26", "fixtures_01_27", "fixtures_01_28", "fixtures_01_32", "fixtures_01_34", "fixtures_01_38"} }}
overlayMap["melos_tiles_furniture_bathroom_04_99"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_24", "fixtures_01_25", "fixtures_01_27", "fixtures_01_31", "fixtures_01_32", "fixtures_01_33", "fixtures_01_35", "fixtures_01_39"} }}
overlayMap["melos_tiles_furniture_bathroom_04_100"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_27", "fixtures_01_35", "fixtures_01_36"} }}
overlayMap["melos_tiles_furniture_bathroom_04_101"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_25", "fixtures_01_29", "fixtures_01_33", "fixtures_01_35", "fixtures_01_37"} }}
overlayMap["melos_tiles_furniture_bathroom_04_102"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_24", "fixtures_01_26", "fixtures_01_28", "fixtures_01_30", "fixtures_01_32", "fixtures_01_34", "fixtures_01_38"} }}
overlayMap["melos_tiles_furniture_bathroom_04_103"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_27", "fixtures_01_31", "fixtures_01_39"} }}
overlayMap["melos_tiles_furniture_bathroom_04_104"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_20"} }}
overlayMap["melos_tiles_furniture_bathroom_04_105"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_10", "fixtures_01_14", "fixtures_01_21"} }}
overlayMap["melos_tiles_furniture_bathroom_04_106"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_19", "fixtures_01_20"} }}
overlayMap["melos_tiles_furniture_bathroom_04_107"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_18", "fixtures_01_22"} }}
overlayMap["melos_tiles_furniture_bathroom_04_108"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_16", "fixtures_01_4", "fixtures_01_20"} }}
overlayMap["melos_tiles_furniture_bathroom_04_109"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_5", "fixtures_01_21"} }}
overlayMap["melos_tiles_furniture_bathroom_04_110"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_18", "fixtures_01_21", "fixtures_01_7"} }}
overlayMap["melos_tiles_furniture_bathroom_04_111"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_6", "fixtures_01_19"} }}
overlayMap["melos_tiles_furniture_bathroom_04_112"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_23"} }}
overlayMap["melos_tiles_furniture_bathroom_04_113"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_22"} }}
overlayMap["melos_tiles_furniture_bathroom_04_114"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_23"} }}
overlayMap["melos_tiles_furniture_bathroom_04_115"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_22"} }}
overlayMap["melos_tiles_furniture_bathroom_04_116"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_23"} }}
overlayMap["melos_tiles_furniture_bathroom_04_117"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_22"} }}
overlayMap["melos_tiles_furniture_bathroom_04_118"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_22"} }}
overlayMap["melos_tiles_furniture_bathroom_04_119"] = {{ name = "other", chance = 1, usage = "", tiles = {"fixtures_01_23"} }}
overlayMap["melos_tiles_furniture_random_01_88"] = {{ name = "other", chance = 1, usage = "", tiles = {"storage_01_22", "storage_01_18", "storage_01_62", "storage_01_34"} }}
overlayMap["melos_tiles_furniture_random_01_89"] = {{ name = "other", chance = 1, usage = "", tiles = {"storage_01_19", "storage_01_23", "storage_01_43", "storage_01_63", "storage_01_66"} }}
overlayMap["melos_tiles_furniture_random_01_90"] = {{ name = "other", chance = 1, usage = "", tiles = {"storage_01_0", "storage_01_1", "storage_01_4", "storage_01_50", "storage_01_70"} }}
overlayMap["melos_tiles_furniture_random_01_91"] = {{ name = "other", chance = 1, usage = "", tiles = {"storage_01_7", "storage_01_5", "storage_01_71", "storage_01_1"} }}

if not TILEZED then
	getTileOverlays():addOverlays(overlayMap)
end

return overlayMap
