local group = AttachedLocations.getGroup("Human")

group:getOrCreateLocation("BeltTorchLeft"):setAttachmentName("torch_left")
group:getOrCreateLocation("BeltTorchRight"):setAttachmentName("torch_right")
group:getOrCreateLocation("BeltTorchLeftSmall"):setAttachmentName("torch_left_small")
group:getOrCreateLocation("BeltTorchLeftVerySmall"):setAttachmentName("torch_left_verysmall")
group:getOrCreateLocation("BeltTorchRightSmall"):setAttachmentName("torch_right_small")
group:getOrCreateLocation("BeltTorchRightVerySmall"):setAttachmentName("torch_right_verysmall")
group:getOrCreateLocation("BeltTorchLeftAngled"):setAttachmentName("torch_left_angled")
group:getOrCreateLocation("BeltTorchRightAngled"):setAttachmentName("torch_right_angled")
group:getOrCreateLocation("WebbingTorchLeftAngled"):setAttachmentName("webbing_left_walkie")
group:getOrCreateLocation("WebbingTorchRightAngled"):setAttachmentName("webbing_right_walkie")
group:getOrCreateLocation("AZMilitaryBeltLeft"):setAttachmentName("AZ_Torch_Belt_Left")
group:getOrCreateLocation("AZMilitaryBeltRight"):setAttachmentName("AZ_Torch_Belt_Right")
