require "Items/ProceduralDistributions"
-- damnCraft.SteelRimSmall
table.insert(ProceduralDistributions.list["CarTiresNormal2"].items, "damnCraft.SteelRimSmall");
table.insert(ProceduralDistributions.list["CarTiresNormal2"].items, 3);
table.insert(ProceduralDistributions.list["CrateMetalwork"].items, "damnCraft.SteelRimSmall");
table.insert(ProceduralDistributions.list["CrateMetalwork"].items, 6);
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "damnCraft.SteelRimSmall");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.3);
table.insert(ProceduralDistributions.list["MechanicShelfWheels"].items, "damnCraft.SteelRimSmall");
table.insert(ProceduralDistributions.list["MechanicShelfWheels"].items, 2);
-- damnCraft.SteelRimMedium
table.insert(ProceduralDistributions.list["CarTiresModern2"].items, "damnCraft.SteelRimMedium");
table.insert(ProceduralDistributions.list["CarTiresModern2"].items, 3);
table.insert(ProceduralDistributions.list["CrateMetalwork"].items, "damnCraft.SteelRimMedium");
table.insert(ProceduralDistributions.list["CrateMetalwork"].items, 7);
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "damnCraft.SteelRimMedium");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.4);
table.insert(ProceduralDistributions.list["MechanicShelfWheels"].items, "damnCraft.SteelRimMedium");
table.insert(ProceduralDistributions.list["MechanicShelfWheels"].items, 2);
-- damnCraft.SteelRimLarge
table.insert(ProceduralDistributions.list["CarTiresModern2"].items, "damnCraft.SteelRimLarge");
table.insert(ProceduralDistributions.list["CarTiresModern2"].items, 3);
table.insert(ProceduralDistributions.list["CrateMetalwork"].items, "damnCraft.SteelRimLarge");
table.insert(ProceduralDistributions.list["CrateMetalwork"].items, 5);
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "damnCraft.SteelRimLarge");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.2);
table.insert(ProceduralDistributions.list["MechanicShelfWheels"].items, "damnCraft.SteelRimLarge");
table.insert(ProceduralDistributions.list["MechanicShelfWheels"].items, 2);
-- damnCraft.TireRubberNewSmall
table.insert(ProceduralDistributions.list["CarTiresNormal2"].items, "damnCraft.TireRubberNewSmall");
table.insert(ProceduralDistributions.list["CarTiresNormal2"].items, 2);
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "damnCraft.TireRubberNewSmall");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.2);
table.insert(ProceduralDistributions.list["MechanicShelfWheels"].items, "damnCraft.TireRubberNewSmall");
table.insert(ProceduralDistributions.list["MechanicShelfWheels"].items, 1);
-- damnCraft.TireRubberUsedSmall
table.insert(ProceduralDistributions.list["CrateRandomJunk"].items, "damnCraft.TireRubberUsedSmall");
table.insert(ProceduralDistributions.list["CrateRandomJunk"].items, 0.1);
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "damnCraft.TireRubberUsedSmall");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.2);
-- damnCraft.TireRubberDestroyedSmall
table.insert(ProceduralDistributions.list["CrateRandomJunk"].items, "damnCraft.TireRubberDestroyedSmall");
table.insert(ProceduralDistributions.list["CrateRandomJunk"].items, 0.1);
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "damnCraft.TireRubberDestroyedSmall");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.3);
table.insert(ProceduralDistributions.list["JunkBin"].items, "damnCraft.TireRubberDestroyedSmall");
table.insert(ProceduralDistributions.list["JunkBin"].items, 8);
-- damnCraft.TireRubberNewLarge
table.insert(ProceduralDistributions.list["CarTiresModern2"].items, "damnCraft.TireRubberNewLarge");
table.insert(ProceduralDistributions.list["CarTiresModern2"].items, 3);
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "damnCraft.TireRubberNewLarge");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.2);
table.insert(ProceduralDistributions.list["MechanicShelfWheels"].items, "damnCraft.TireRubberNewLarge");
table.insert(ProceduralDistributions.list["MechanicShelfWheels"].items, 2);
-- damnCraft.TireRubberUsedLarge
table.insert(ProceduralDistributions.list["CrateRandomJunk"].items, "damnCraft.TireRubberUsedLarge");
table.insert(ProceduralDistributions.list["CrateRandomJunk"].items, 0.1);
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "damnCraft.TireRubberUsedLarge");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.3);
-- damnCraft.TireRubberDestroyedLarge
table.insert(ProceduralDistributions.list["CrateRandomJunk"].items, "damnCraft.TireRubberDestroyedLarge");
table.insert(ProceduralDistributions.list["CrateRandomJunk"].items, 0.1);
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "damnCraft.TireRubberDestroyedLarge");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.3);
table.insert(ProceduralDistributions.list["JunkBin"].items, "damnCraft.TireRubberDestroyedLarge");
table.insert(ProceduralDistributions.list["JunkBin"].items, 8);
-- damnCraft.TireRubberMountSmall
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "damnCraft.TireRubberMountSmall");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.3);
-- damnCraft.TireRubberMountLarge
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "damnCraft.TireRubberMountLarge");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.3);
-- damnCraft.HandleClassic
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "damnCraft.HandleClassic");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 7);
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "damnCraft.HandleClassic");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.5);
-- damnCraft.HandleModern
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "damnCraft.HandleModern");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 7);
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "damnCraft.HandleModern");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.5);
-- damnCraft.HingeSmall
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "damnCraft.HingeSmall");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 7);
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "damnCraft.HingeSmall");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.5);
-- damnCraft.HingeLarge
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "damnCraft.HingeLarge");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 7);
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "damnCraft.HingeLarge");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.5);
-- damnCraft.RubberStrip
table.insert(ProceduralDistributions.list["CarTiresModern1"].items, "damnCraft.RubberStrip");
table.insert(ProceduralDistributions.list["CarTiresModern1"].items, 2);
table.insert(ProceduralDistributions.list["CarTiresModern2"].items, "damnCraft.RubberStrip");
table.insert(ProceduralDistributions.list["CarTiresModern2"].items, 3);
table.insert(ProceduralDistributions.list["CarTiresModern3"].items, "damnCraft.RubberStrip");
table.insert(ProceduralDistributions.list["CarTiresModern3"].items, 1);
table.insert(ProceduralDistributions.list["CarTiresNormal1"].items, "damnCraft.RubberStrip");
table.insert(ProceduralDistributions.list["CarTiresNormal1"].items, 2);
table.insert(ProceduralDistributions.list["CarTiresNormal2"].items, "damnCraft.RubberStrip");
table.insert(ProceduralDistributions.list["CarTiresNormal2"].items, 3);
table.insert(ProceduralDistributions.list["CarTiresNormal3"].items, "damnCraft.RubberStrip");
table.insert(ProceduralDistributions.list["CarTiresNormal3"].items, 1);
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "damnCraft.RubberStrip");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.2);
table.insert(ProceduralDistributions.list["MechanicShelfWheels"].items, "damnCraft.RubberStrip");
table.insert(ProceduralDistributions.list["MechanicShelfWheels"].items, 2);
-- damnCraft.SeatFabric
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "damnCraft.SeatFabric");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 5);
table.insert(ProceduralDistributions.list["CrateTailoring"].items, "damnCraft.SeatFabric");
table.insert(ProceduralDistributions.list["CrateTailoring"].items, 5);
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "damnCraft.SeatFabric");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.4);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "damnCraft.SeatFabric");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 4);
-- damnCraft.SeatFoam
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "damnCraft.SeatFoam");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 6);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "damnCraft.SeatFoam");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 3);
-- damnCraft.SeatFrameSmall
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "damnCraft.SeatFrameSmall");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 4);
table.insert(ProceduralDistributions.list["CrateMetalwork"].items, "damnCraft.SeatFrameSmall");
table.insert(ProceduralDistributions.list["CrateMetalwork"].items, 6);
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "damnCraft.SeatFrameSmall");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.4);
table.insert(ProceduralDistributions.list["GarageMetalwork"].items, "damnCraft.SeatFrameSmall");
table.insert(ProceduralDistributions.list["GarageMetalwork"].items, 0.3);
-- damnCraft.SeatFrameLarge
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "damnCraft.SeatFrameLarge");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 5);
table.insert(ProceduralDistributions.list["CrateMetalwork"].items, "damnCraft.SeatFrameLarge");
table.insert(ProceduralDistributions.list["CrateMetalwork"].items, 7);
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "damnCraft.SeatFrameLarge");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.4);
table.insert(ProceduralDistributions.list["GarageMetalwork"].items, "damnCraft.SeatFrameLarge");
table.insert(ProceduralDistributions.list["GarageMetalwork"].items, 0.4);
-- damnCraft.TireRepairKit
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "damnCraft.TireRepairKit");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.5);
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "damnCraft.TireRepairKit");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 5);
table.insert(ProceduralDistributions.list["ArmyHangarTools"].items, "damnCraft.TireRepairKit");
table.insert(ProceduralDistributions.list["ArmyHangarTools"].items, 2);
table.insert(ProceduralDistributions.list["CarSupplyTools"].items, "damnCraft.TireRepairKit");
table.insert(ProceduralDistributions.list["CarSupplyTools"].items, 4);
table.insert(ProceduralDistributions.list["GarageTools"].items, "damnCraft.TireRepairKit");
table.insert(ProceduralDistributions.list["GarageTools"].items, 3);
table.insert(ProceduralDistributions.list["GigamartTools"].items, "damnCraft.TireRepairKit");
table.insert(ProceduralDistributions.list["GigamartTools"].items, 4);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "damnCraft.TireRepairKit");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 6);
table.insert(ProceduralDistributions.list["ToolStoreTools"].items, "damnCraft.TireRepairKit");
table.insert(ProceduralDistributions.list["ToolStoreTools"].items, 4);
table.insert(ProceduralDistributions.list["SurvivalGear"].items, "damnCraft.TireRepairKit");
table.insert(ProceduralDistributions.list["SurvivalGear"].items, 1);
-- damnCraft.TireRepairTools
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "damnCraft.TireRepairTools");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.3);
-- damnCraft.TireRepairRubberSolution
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "damnCraft.TireRepairRubberSolution");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.3);
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "damnCraft.TireRepairRubberSolution");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 3);
table.insert(ProceduralDistributions.list["CarSupplyTools"].items, "damnCraft.TireRepairRubberSolution");
table.insert(ProceduralDistributions.list["CarSupplyTools"].items, 4);
table.insert(ProceduralDistributions.list["GarageTools"].items, "damnCraft.TireRepairRubberSolution");
table.insert(ProceduralDistributions.list["GarageTools"].items, 4);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "damnCraft.TireRepairRubberSolution");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 8);
-- damnCraft.TireRepairStrips
table.insert(ProceduralDistributions.list["GarageTools"].items, "damnCraft.TireRepairStrips");
table.insert(ProceduralDistributions.list["GarageTools"].items, 5);
-- damnCraft.PlasticWeldingKit
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "damnCraft.PlasticWeldingKit");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.5);
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "damnCraft.PlasticWeldingKit");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 4);
table.insert(ProceduralDistributions.list["ArmyHangarTools"].items, "damnCraft.PlasticWeldingKit");
table.insert(ProceduralDistributions.list["ArmyHangarTools"].items, 3);
table.insert(ProceduralDistributions.list["CarSupplyTools"].items, "damnCraft.PlasticWeldingKit");
table.insert(ProceduralDistributions.list["CarSupplyTools"].items, 4);
table.insert(ProceduralDistributions.list["CrateTools"].items, "damnCraft.PlasticWeldingKit");
table.insert(ProceduralDistributions.list["CrateTools"].items, 1);
table.insert(ProceduralDistributions.list["GarageTools"].items, "damnCraft.PlasticWeldingKit");
table.insert(ProceduralDistributions.list["GarageTools"].items, 3);
table.insert(ProceduralDistributions.list["GigamartTools"].items, "damnCraft.PlasticWeldingKit");
table.insert(ProceduralDistributions.list["GigamartTools"].items, 2);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "damnCraft.PlasticWeldingKit");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 3);
table.insert(ProceduralDistributions.list["ToolStoreTools"].items, "damnCraft.PlasticWeldingKit");
table.insert(ProceduralDistributions.list["ToolStoreTools"].items, 3);
table.insert(ProceduralDistributions.list["SurvivalGear"].items, "damnCraft.PlasticWeldingKit");
table.insert(ProceduralDistributions.list["SurvivalGear"].items, 1);
-- damnCraft.acetoneCan
table.insert(ProceduralDistributions.list["ArmyBunkerStorage"].items, "damnCraft.acetoneCan");
table.insert(ProceduralDistributions.list["ArmyBunkerStorage"].items, 0.8);
table.insert(ProceduralDistributions.list["BinHospital"].items, "damnCraft.acetoneCan");
table.insert(ProceduralDistributions.list["BinHospital"].items, 2);
table.insert(ProceduralDistributions.list["Chemistry"].items, "damnCraft.acetoneCan");
table.insert(ProceduralDistributions.list["Chemistry"].items, 9);
table.insert(ProceduralDistributions.list["DrugLabSupplies"].items, "damnCraft.acetoneCan");
table.insert(ProceduralDistributions.list["DrugLabSupplies"].items, 7);
table.insert(ProceduralDistributions.list["FossoilCounterCleaning"].items, "damnCraft.acetoneCan");
table.insert(ProceduralDistributions.list["FossoilCounterCleaning"].items, 7);
table.insert(ProceduralDistributions.list["Gas2GoCounterCleaning"].items, "damnCraft.acetoneCan");
table.insert(ProceduralDistributions.list["Gas2GoCounterCleaning"].items, 7);
table.insert(ProceduralDistributions.list["GasStoreCounterCleaning"].items, "damnCraft.acetoneCan");
table.insert(ProceduralDistributions.list["GasStoreCounterCleaning"].items, 7);
table.insert(ProceduralDistributions.list["GigamartCleaning"].items, "damnCraft.acetoneCan");
table.insert(ProceduralDistributions.list["GigamartCleaning"].items, 18);
table.insert(ProceduralDistributions.list["HospitalRoomCleaning"].items, "damnCraft.acetoneCan");
table.insert(ProceduralDistributions.list["HospitalRoomCleaning"].items, 8);
table.insert(ProceduralDistributions.list["JanitorChemicals"].items, "damnCraft.acetoneCan");
table.insert(ProceduralDistributions.list["JanitorChemicals"].items, 20);
table.insert(ProceduralDistributions.list["JanitorCleaning"].items, "damnCraft.acetoneCan");
table.insert(ProceduralDistributions.list["JanitorCleaning"].items, 8);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "damnCraft.acetoneCan");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 3);
table.insert(ProceduralDistributions.list["MorgueChemicals"].items, "damnCraft.acetoneCan");
table.insert(ProceduralDistributions.list["MorgueChemicals"].items, 10);
-- damnCraft.acetoneJug
table.insert(ProceduralDistributions.list["ArmyBunkerStorage"].items, "damnCraft.acetoneJug");
table.insert(ProceduralDistributions.list["ArmyBunkerStorage"].items, 0.6);
table.insert(ProceduralDistributions.list["BinHospital"].items, "damnCraft.acetoneJug");
table.insert(ProceduralDistributions.list["BinHospital"].items, 1.8);
table.insert(ProceduralDistributions.list["Chemistry"].items, "damnCraft.acetoneJug");
table.insert(ProceduralDistributions.list["Chemistry"].items, 7);
table.insert(ProceduralDistributions.list["DrugLabSupplies"].items, "damnCraft.acetoneJug");
table.insert(ProceduralDistributions.list["DrugLabSupplies"].items, 5);
table.insert(ProceduralDistributions.list["FossoilCounterCleaning"].items, "damnCraft.acetoneJug");
table.insert(ProceduralDistributions.list["FossoilCounterCleaning"].items, 5);
table.insert(ProceduralDistributions.list["Gas2GoCounterCleaning"].items, "damnCraft.acetoneJug");
table.insert(ProceduralDistributions.list["Gas2GoCounterCleaning"].items, 5);
table.insert(ProceduralDistributions.list["GasStoreCounterCleaning"].items, "damnCraft.acetoneJug");
table.insert(ProceduralDistributions.list["GasStoreCounterCleaning"].items, 5);
table.insert(ProceduralDistributions.list["GigamartCleaning"].items, "damnCraft.acetoneJug");
table.insert(ProceduralDistributions.list["GigamartCleaning"].items, 12);
table.insert(ProceduralDistributions.list["HospitalRoomCleaning"].items, "damnCraft.acetoneJug");
table.insert(ProceduralDistributions.list["HospitalRoomCleaning"].items, 7);
table.insert(ProceduralDistributions.list["JanitorChemicals"].items, "damnCraft.acetoneJug");
table.insert(ProceduralDistributions.list["JanitorChemicals"].items, 18);
table.insert(ProceduralDistributions.list["JanitorCleaning"].items, "damnCraft.acetoneJug");
table.insert(ProceduralDistributions.list["JanitorCleaning"].items, 7);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "damnCraft.acetoneJug");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 2);
table.insert(ProceduralDistributions.list["MorgueChemicals"].items, "damnCraft.acetoneJug");
table.insert(ProceduralDistributions.list["MorgueChemicals"].items, 7);
-- damnCraft.styrofoamSheet
table.insert(ProceduralDistributions.list["CrateRandomJunk"].items, "damnCraft.styrofoamSheet");
table.insert(ProceduralDistributions.list["CrateRandomJunk"].items, 0.9);
table.insert(ProceduralDistributions.list["CrateTools"].items, "damnCraft.styrofoamSheet");
table.insert(ProceduralDistributions.list["CrateTools"].items, 4);
table.insert(ProceduralDistributions.list["CrateToolsOld"].items, "damnCraft.styrofoamSheet");
table.insert(ProceduralDistributions.list["CrateToolsOld"].items, 6);
table.insert(ProceduralDistributions.list["GigamartTools"].items, "damnCraft.styrofoamSheet");
table.insert(ProceduralDistributions.list["GigamartTools"].items, 9);
table.insert(ProceduralDistributions.list["ToolStoreMisc"].items, "damnCraft.styrofoamSheet");
table.insert(ProceduralDistributions.list["ToolStoreMisc"].items, 12);
table.insert(ProceduralDistributions.list["ArtSupplies"].items, "damnCraft.styrofoamSheet");
table.insert(ProceduralDistributions.list["ArtSupplies"].items, 7);
table.insert(ProceduralDistributions.list["CrateWallFinish"].items, "damnCraft.styrofoamSheet");
table.insert(ProceduralDistributions.list["CrateWallFinish"].items, 2);